export const BANNED_ROOM_IDS = ['EFYXT4CX', 'HNAY9U4C'];
export const POLL_INTERVAL_MS = 3000;
export const ACTIVE_ROOM_POLL_INTERVAL_MS = 1200;
export const MAX_MESSAGE_LENGTH = 500;
export const DRAWING_WIDTH = 1000;
export const DRAWING_HEIGHT = 1000;
export const MAX_DRAWING_DATA_URL_LENGTH = 2500000;
export const TYPING_DEBOUNCE_MS = 1200;
export const DRAWING_COLORS = [
  '#000000', '#ffffff', '#ef4444', '#f97316', '#eab308', '#22c55e', '#3b82f6', '#a855f7', '#ec4899'
];

export const DEFAULT_CHAT_COPY = {
  headerLabel: 'Character chat',
  title: 'Character chat',
  subtitle: 'Pick a portrait card, open a room or join one with a code, and chat in one shared thread.',
  roomRule: 'Each room stays active until the creator ends it. Anyone with the room code can join the thread.',
  safetyTitle: 'Safety first',
  safetyNotice: [
    'Only role-play with clear consent and with people you trust.',
    'Do not pressure anyone into romance, sexual content, personal disclosure, or continued contact.',
    'Stop immediately if the chat becomes abusive, humiliating, threatening, manipulative, or bullying.',
    'Do not share real private information, location, school, workplace, passwords, or financial details.',
    'Leave the room and block/report the person if you feel unsafe, distressed, or targeted.',
  ],
  yourRooms: 'Your rooms',
  publicRooms: 'Public rooms',
  roomDirectory: 'Room directory',
  featuredRooms: 'Discover live public rooms and your saved spaces in one list.',
  searchRooms: 'Search rooms',
  noRooms: 'No rooms available',
  roomInfoTitle: 'Room info',
  roomInfoHint: 'Open the full chat view to talk, draw, and manage the live room without exposing the room code.',
  roomMessagesLabel: 'Messages',
  roomUpdatedLabel: 'Last update',
  roomCharacterLabel: 'Character',
  roomMembersLabel: 'Members',
  visibilityLabel: 'Visibility',
  publicRoom: 'Public',
  privateRoom: 'Private',
  visibilityHint: 'Room visibility is still code-based. Only people with the room code can enter.',
  publicHint: 'Public rooms are visible to everyone here. Private rooms stay local unless you have the code.',
  noRoomsSaved: 'Rooms you create or join on this device will stay here until they end.',
  noPublicRooms: 'No public rooms are live right now.',
  openChat: 'Open chat',
  copyChat: 'Copy chat',
  roomControls: 'Room controls',
  peopleLabel: 'People',
  personLabel: 'Person',
  luckyPick: "I'm feeling lucky",
  exitCharacter: 'Exit character',
  createLabel: 'Create room',
  joinLabel: 'Join room',
  reconnectLabel: 'Reconnect',
  roomDirectoryHeading: 'Chat',
  roomTitleLabel: 'Room title',
  roomTitleRequired: 'Add a room name before opening the room.',
  roomCodeRequired: 'Enter a room code.',
  roomCodeInvalid: 'Enter a valid room code.',
  roomCodeLabel: 'Room code',
  portraitLabel: 'Choose your portrait card',
  roomTitlePlaceholder: 'After school rooftop',
  roomCodePlaceholder: 'ABCD-1234',
  messagePlaceholder: 'Message...',
  createAction: 'Open room',
  joinAction: 'Enter room',
  copyCode: 'Copy code',
  refresh: 'Refresh',
  leaveView: 'Leave view',
  endRoom: 'End room',
  exitLabel: 'Exit room',
  you: 'You',
  waiting: 'Waiting for more players to join.',
  activePlayers: 'Players',
  liveRoom: 'Live room',
  latestUpdate: 'Latest update',
  noMessages: 'The room is open. Drop the first message when you are ready.',
  sendAction: 'Send',
  lastRoom: 'Last active room',
  reconnectHint: 'Reconnect to the last room you joined from this browser.',
  noSavedRoom: 'No active room saved',
  roomCodeCopyError: 'Could not copy the room code from this browser.',
  roomChatCopyError: 'Could not copy the room chat from this browser.',
  copiedRoomCodeStatus: 'Copied {roomId}.',
  copiedRoomChatStatus: 'Copied chat from {roomTitle}.',
  roomLiveStatus: 'Room {roomId} is live.',
  joinedRoomStatus: 'Joined {roomId}.',
  reconnectedRoomStatus: 'Reconnected to {roomId}.',
  roomRefreshedStatus: 'Room {roomId} refreshed.',
  roomInactiveStatus: 'Room {roomId} is no longer active.',
  identityReclaimed: 'Identity reclaimed successfully!',
  failedToRedeemKey: 'Failed to redeem key',
  drawingLabel: 'Drawing',
  drawAction: 'Draw',
  clearDrawing: 'Clear',
  removeDrawing: 'Remove',
  drawingBrush: 'Brush',
  drawingEraser: 'Eraser',
  drawingFill: 'Fill',
  drawingUndo: 'Undo',
  drawingRedo: 'Redo',
  drawingDone: 'Done',
  tapToClear: 'Tap {count}x',
  doneShort: 'Done!',
  doneLong: "I'm done!",
  fillCanvasConfirm: 'Fill the entire canvas with the current color?',
  roomCreatorLabel: 'Room creator',
  messageSideLabel: 'Message side (your messages)',
  messageSideRight: 'Right (Default)',
  messageSideLeft: 'Left (Alternative)',
  settingsLabel: 'Settings',
  closeLabel: 'Close',
  backLabel: 'Back',
  noSyncKey: 'No sync key',
  security: 'Sync & identity',
  lobbyCreateHint: 'Configure your new room in the lobby...',
  lobbyJoinHint: 'Enter a code to join a room...',
  unknownUser: 'Unknown',
  syncKeyDetails: 'The Sync tab gives you additional tools to manage your character cloud presence and reading history.',
  roomDirectoryTab: 'Room directory',
};

export const PANEL_STYLE = {
  background: '#fffefc',
  border: '3px solid #cbd5e1',
  borderBottom: '8px solid #94a3b8',
  borderRadius: '28px',
  boxShadow: '0 18px 42px rgba(15, 23, 42, 0.12)',
};

export const CHAT_FONT_FAMILY = "'Sniglet', 'Coming Soon', 'Pangolin', 'Comic Neue', 'Comic Sans MS', cursive, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Noto Color Emoji', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'";

export const INPUT_STYLE = {
  width: '100%',
  border: '2.5px solid #dbe7f3',
  borderBottom: '5px solid #c7d7ea',
  borderRadius: '16px',
  background: '#ffffff',
  color: '#1e293b',
  padding: '12px 14px',
  fontFamily: CHAT_FONT_FAMILY,
  fontSize: '1.04rem',
  fontWeight: 400,
  lineHeight: 1.4,
  outline: 'none',
};

export const BUTTON_STYLE = {
  border: '3px solid #0f172a',
  borderBottom: '7px solid #0f172a',
  borderRadius: '18px',
  cursor: 'pointer',
  fontFamily: CHAT_FONT_FAMILY,
  fontWeight: 400,
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: '8px',
  lineHeight: 1,
};

export const SPIN_ICON_STYLE = {
  animation: 'spin 0.9s linear infinite',
};

const CHAT_COPY_BY_LANGUAGE = {
  es: {
    headerLabel: 'Chat de personajes',
    title: 'Chat de personajes',
    roomDirectory: 'Directorio de salas',
    featuredRooms: 'Descubre salas públicas en vivo y tus espacios guardados en una sola lista.',
    searchRooms: 'Buscar salas',
    noRooms: 'No hay salas disponibles',
    noRoomsSaved: 'Las salas que crees o a las que te unas en este dispositivo se quedarán aquí hasta que terminen.',
    noPublicRooms: 'Ahora mismo no hay salas públicas en vivo.',
    copyChat: 'Copiar chat',
    roomControls: 'Controles de la sala',
    peopleLabel: 'Personas',
    exitCharacter: 'Salir del personaje',
    createLabel: 'Crear sala',
    joinLabel: 'Unirse a la sala',
    reconnectLabel: 'Reconectar',
    roomDirectoryHeading: 'Chat',
    roomTitleLabel: 'Título de la sala',
    roomTitleRequired: 'Añade un nombre antes de abrir la sala.',
    roomCodeRequired: 'Introduce un código de sala.',
    roomCodeInvalid: 'Introduce un código de sala válido.',
    roomCodeLabel: 'Código de la sala',
    portraitLabel: 'Elige tu tarjeta de retrato',
    roomTitlePlaceholder: 'Azotea después de clases',
    roomCodePlaceholder: 'ABCD-1234',
    messagePlaceholder: 'Mensaje...',
    createAction: 'Abrir sala',
    joinAction: 'Entrar en la sala',
    copyCode: 'Copiar código',
    refresh: 'Actualizar',
    leaveView: 'Salir de la vista',
    endRoom: 'Cerrar sala',
    exitLabel: 'Salir de la sala',
    drawingBrush: 'Pincel',
    drawingEraser: 'Borrador',
    drawingFill: 'Rellenar',
    drawingUndo: 'Deshacer',
    drawingRedo: 'Rehacer',
    clearDrawing: 'Borrar',
    removeDrawing: 'Eliminar',
    drawingDone: 'Hecho',
    tapToClear: 'Toca {count}x',
    doneShort: '¡Hecho!',
    doneLong: '¡Terminé!',
    fillCanvasConfirm: '¿Rellenar todo el lienzo con el color actual?',
    roomCreatorLabel: 'Creador de la sala',
    messageSideLabel: 'Lado del mensaje (tus mensajes)',
    messageSideRight: 'Derecha (predeterminado)',
    messageSideLeft: 'Izquierda (alternativa)',
    settingsLabel: 'Ajustes',
    closeLabel: 'Cerrar',
    backLabel: 'Atrás',
    noSyncKey: 'Sin clave de sincronización',
    security: 'Sincronización e identidad',
    lobbyCreateHint: 'Configura tu nueva sala en el lobby...',
    lobbyJoinHint: 'Introduce un código para unirte a una sala...',
    syncKeyHint: 'Esta clave de la pestaña Progreso vincula tu identidad, tus elecciones de personaje y el historial de salas en todos tus dispositivos.',
    syncKeyDetails: 'La pestaña Sincronización te da más herramientas para gestionar la presencia en la nube de tu personaje y el historial de lectura.',
    roomCodeCopyError: 'No se pudo copiar el código de la sala desde este navegador.',
    roomChatCopyError: 'No se pudo copiar el chat de la sala desde este navegador.',
    copiedRoomCodeStatus: 'Se copió {roomId}.',
    copiedRoomChatStatus: 'Se copió el chat de {roomTitle}.',
    roomLiveStatus: 'La sala {roomId} está en vivo.',
    joinedRoomStatus: 'Te has unido a {roomId}.',
    reconnectedRoomStatus: 'Reconectado a {roomId}.',
    roomRefreshedStatus: 'La sala {roomId} se actualizó.',
    roomInactiveStatus: 'La sala {roomId} ya no está activa.',
    identityReclaimed: '¡Identidad recuperada con éxito!',
    failedToRedeemKey: 'No se pudo canjear la clave',
    unknownUser: 'Desconocido',
    roomDirectoryTab: 'Directorio de salas',
  },
  pt: {
    headerLabel: 'Chat de personagens',
    title: 'Chat de personagens',
    roomDirectory: 'Diretório de salas',
    featuredRooms: 'Descubra salas públicas ao vivo e seus espaços salvos em uma única lista.',
    searchRooms: 'Buscar salas',
    noRooms: 'Nenhuma sala disponível',
    noRoomsSaved: 'As salas que você criar ou entrar neste dispositivo ficarão aqui até terminarem.',
    noPublicRooms: 'Não há salas públicas ao vivo no momento.',
    copyChat: 'Copiar chat',
    roomControls: 'Controles da sala',
    peopleLabel: 'Pessoas',
    exitCharacter: 'Sair do personagem',
    createLabel: 'Criar sala',
    joinLabel: 'Entrar na sala',
    reconnectLabel: 'Reconectar',
    roomDirectoryHeading: 'Chat',
    roomTitleLabel: 'Título da sala',
    roomTitleRequired: 'Adicione um nome antes de abrir a sala.',
    roomCodeRequired: 'Digite um código da sala.',
    roomCodeInvalid: 'Digite um código da sala válido.',
    roomCodeLabel: 'Código da sala',
    portraitLabel: 'Escolha seu cartão de retrato',
    roomTitlePlaceholder: 'Terraço depois da aula',
    roomCodePlaceholder: 'ABCD-1234',
    messagePlaceholder: 'Mensagem...',
    createAction: 'Abrir sala',
    joinAction: 'Entrar na sala',
    copyCode: 'Copiar código',
    refresh: 'Atualizar',
    leaveView: 'Sair da visualização',
    endRoom: 'Encerrar sala',
    exitLabel: 'Sair da sala',
    drawingBrush: 'Pincel',
    drawingEraser: 'Borracha',
    drawingFill: 'Preencher',
    drawingUndo: 'Desfazer',
    drawingRedo: 'Refazer',
    clearDrawing: 'Limpar',
    removeDrawing: 'Remover',
    drawingDone: 'Pronto',
    tapToClear: 'Toque {count}x',
    doneShort: 'Pronto!',
    doneLong: 'Terminei!',
    fillCanvasConfirm: 'Preencher toda a tela com a cor atual?',
    roomCreatorLabel: 'Criador da sala',
    messageSideLabel: 'Lado da mensagem (suas mensagens)',
    messageSideRight: 'Direita (padrão)',
    messageSideLeft: 'Esquerda (alternativa)',
    settingsLabel: 'Configurações',
    closeLabel: 'Fechar',
    backLabel: 'Voltar',
    noSyncKey: 'Sem chave de sincronização',
    security: 'Sincronização e identidade',
    lobbyCreateHint: 'Configure sua nova sala no lobby...',
    lobbyJoinHint: 'Digite um código para entrar em uma sala...',
    syncKeyHint: 'Esta chave da aba Progresso vincula sua identidade, escolhas de personagem e histórico de salas em todos os seus dispositivos.',
    syncKeyDetails: 'A aba Sincronização oferece ferramentas adicionais para gerenciar a presença em nuvem do seu personagem e o histórico de leitura.',
    roomCodeCopyError: 'Não foi possível copiar o código da sala neste navegador.',
    roomChatCopyError: 'Não foi possível copiar o chat da sala neste navegador.',
    copiedRoomCodeStatus: 'Copiado {roomId}.',
    copiedRoomChatStatus: 'Chat copiado de {roomTitle}.',
    roomLiveStatus: 'A sala {roomId} está ao vivo.',
    joinedRoomStatus: 'Entrou em {roomId}.',
    reconnectedRoomStatus: 'Reconectado a {roomId}.',
    roomRefreshedStatus: 'A sala {roomId} foi atualizada.',
    roomInactiveStatus: 'A sala {roomId} não está mais ativa.',
    identityReclaimed: 'Identidade recuperada com sucesso!',
    failedToRedeemKey: 'Falha ao resgatar a chave',
    unknownUser: 'Desconhecido',
    roomDirectoryTab: 'Diretório de salas',
  },
  fr: {
    headerLabel: 'Chat des personnages',
    title: 'Chat des personnages',
    roomDirectory: 'Répertoire des salles',
    featuredRooms: 'Découvre les salles publiques en direct et tes espaces enregistrés dans une seule liste.',
    searchRooms: 'Rechercher des salles',
    noRooms: 'Aucune salle disponible',
    noRoomsSaved: 'Les salles que tu crées ou rejoins sur cet appareil resteront ici jusqu’à leur fin.',
    noPublicRooms: 'Aucune salle publique en direct pour le moment.',
    copyChat: 'Copier le chat',
    roomControls: 'Contrôles de la salle',
    peopleLabel: 'Personnes',
    exitCharacter: 'Quitter le personnage',
    createLabel: 'Créer une salle',
    joinLabel: 'Rejoindre une salle',
    reconnectLabel: 'Reconnecter',
    roomDirectoryHeading: 'Chat',
    roomTitleLabel: 'Titre de la salle',
    roomTitleRequired: 'Ajoute un nom avant d’ouvrir la salle.',
    roomCodeRequired: 'Entre un code de salle.',
    roomCodeInvalid: 'Entre un code de salle valide.',
    roomCodeLabel: 'Code de la salle',
    portraitLabel: 'Choisis ta carte portrait',
    roomTitlePlaceholder: "Toit après les cours",
    roomCodePlaceholder: 'ABCD-1234',
    messagePlaceholder: 'Message...',
    createAction: 'Ouvrir la salle',
    joinAction: 'Entrer dans la salle',
    copyCode: 'Copier le code',
    refresh: 'Actualiser',
    leaveView: 'Quitter la vue',
    endRoom: 'Fermer la salle',
    exitLabel: 'Quitter la salle',
    drawingBrush: 'Pinceau',
    drawingEraser: 'Gomme',
    drawingFill: 'Remplir',
    drawingUndo: 'Annuler',
    drawingRedo: 'Rétablir',
    clearDrawing: 'Effacer',
    removeDrawing: 'Supprimer',
    drawingDone: 'Terminé',
    tapToClear: 'Tape {count}x',
    doneShort: 'Terminé !',
    doneLong: 'J’ai fini !',
    fillCanvasConfirm: 'Remplir tout le canevas avec la couleur actuelle ?',
    roomCreatorLabel: 'Créateur de la salle',
    messageSideLabel: 'Côté des messages (tes messages)',
    messageSideRight: 'Droite (par défaut)',
    messageSideLeft: 'Gauche (alternative)',
    settingsLabel: 'Paramètres',
    closeLabel: 'Fermer',
    backLabel: 'Retour',
    noSyncKey: 'Aucune clé de synchronisation',
    security: 'Synchronisation et identité',
    lobbyCreateHint: 'Configure ta nouvelle salle dans le hall...',
    lobbyJoinHint: 'Entre un code pour rejoindre une salle...',
    syncKeyHint: 'Cette clé de l’onglet Progression relie ton identité, tes choix de personnage et l’historique des salles sur tous tes appareils.',
    syncKeyDetails: 'L’onglet Synchronisation propose des outils supplémentaires pour gérer la présence cloud de ton personnage et ton historique de lecture.',
    roomCodeCopyError: 'Impossible de copier le code de la salle depuis ce navigateur.',
    roomChatCopyError: 'Impossible de copier le chat de la salle depuis ce navigateur.',
    copiedRoomCodeStatus: '{roomId} copié.',
    copiedRoomChatStatus: 'Chat copié depuis {roomTitle}.',
    roomLiveStatus: 'La salle {roomId} est en direct.',
    joinedRoomStatus: 'Rejoint {roomId}.',
    reconnectedRoomStatus: 'Reconnecté à {roomId}.',
    roomRefreshedStatus: 'La salle {roomId} a été actualisée.',
    roomInactiveStatus: 'La salle {roomId} n’est plus active.',
    identityReclaimed: 'Identité récupérée avec succès !',
    failedToRedeemKey: 'Impossible de récupérer la clé',
    unknownUser: 'Inconnu',
    roomDirectoryTab: 'Répertoire des salles',
  },
  de: {
    headerLabel: 'Charakter-Chat',
    title: 'Charakter-Chat',
    roomDirectory: 'Raumverzeichnis',
    featuredRooms: 'Entdecke öffentliche Live-Räume und deine gespeicherten Räume in einer Liste.',
    searchRooms: 'Räume suchen',
    noRooms: 'Keine Räume verfügbar',
    noRoomsSaved: 'Räume, die du auf diesem Gerät erstellst oder beitrittst, bleiben hier, bis sie enden.',
    noPublicRooms: 'Derzeit sind keine öffentlichen Räume live.',
    copyChat: 'Chat kopieren',
    roomControls: 'Raumsteuerung',
    peopleLabel: 'Personen',
    exitCharacter: 'Charakter verlassen',
    createLabel: 'Raum erstellen',
    joinLabel: 'Raum beitreten',
    reconnectLabel: 'Erneut verbinden',
    roomDirectoryHeading: 'Chat',
    roomTitleLabel: 'Raumtitel',
    roomTitleRequired: 'Bitte gib einen Namen ein, bevor du den Raum öffnest.',
    roomCodeRequired: 'Gib einen Raumcode ein.',
    roomCodeInvalid: 'Gib einen gültigen Raumcode ein.',
    roomCodeLabel: 'Raumcode',
    portraitLabel: 'Wähle deine Portraitkarte',
    roomTitlePlaceholder: 'Dach nach der Schule',
    roomCodePlaceholder: 'ABCD-1234',
    messagePlaceholder: 'Nachricht...',
    createAction: 'Raum öffnen',
    joinAction: 'Raum betreten',
    copyCode: 'Code kopieren',
    refresh: 'Aktualisieren',
    leaveView: 'Ansicht verlassen',
    endRoom: 'Raum beenden',
    exitLabel: 'Raum verlassen',
    drawingBrush: 'Pinsel',
    drawingEraser: 'Radierer',
    drawingFill: 'Füllen',
    drawingUndo: 'Rückgängig',
    drawingRedo: 'Wiederholen',
    clearDrawing: 'Löschen',
    removeDrawing: 'Entfernen',
    drawingDone: 'Fertig',
    tapToClear: 'Tippe {count}x',
    doneShort: 'Fertig!',
    doneLong: 'Ich bin fertig!',
    fillCanvasConfirm: 'Die gesamte Leinwand mit der aktuellen Farbe füllen?',
    roomCreatorLabel: 'Raumersteller',
    messageSideLabel: 'Nachrichtenseite (deine Nachrichten)',
    messageSideRight: 'Rechts (Standard)',
    messageSideLeft: 'Links (Alternative)',
    settingsLabel: 'Einstellungen',
    closeLabel: 'Schließen',
    backLabel: 'Zurück',
    noSyncKey: 'Kein Synchronisierungsschlüssel',
    security: 'Synchronisierung & Identität',
    lobbyCreateHint: 'Konfiguriere deinen neuen Raum in der Lobby...',
    lobbyJoinHint: 'Gib einen Code ein, um einem Raum beizutreten...',
    syncKeyHint: 'Dieser Schlüssel aus deinem Fortschritts-Tab verknüpft deine Identität, Charakterauswahl und Raumhistorie auf allen Geräten.',
    syncKeyDetails: 'Der Synchronisierungs-Tab bietet dir zusätzliche Werkzeuge, um die Cloud-Präsenz deines Charakters und deine Lesegeschichte zu verwalten.',
    roomCodeCopyError: 'Der Raumcode konnte in diesem Browser nicht kopiert werden.',
    roomChatCopyError: 'Der Raumchat konnte in diesem Browser nicht kopiert werden.',
    copiedRoomCodeStatus: '{roomId} kopiert.',
    copiedRoomChatStatus: 'Chat von {roomTitle} kopiert.',
    roomLiveStatus: 'Raum {roomId} ist live.',
    joinedRoomStatus: '{roomId} beigetreten.',
    reconnectedRoomStatus: 'Mit {roomId} erneut verbunden.',
    roomRefreshedStatus: 'Raum {roomId} aktualisiert.',
    roomInactiveStatus: 'Raum {roomId} ist nicht mehr aktiv.',
    identityReclaimed: 'Identität erfolgreich zurückgeholt!',
    failedToRedeemKey: 'Schlüssel konnte nicht eingelöst werden',
    unknownUser: 'Unbekannt',
    roomDirectoryTab: 'Raumverzeichnis',
  },
  it: {
    headerLabel: 'Chat dei personaggi',
    title: 'Chat dei personaggi',
    roomDirectory: 'Elenco stanze',
    featuredRooms: 'Scopri le stanze pubbliche live e i tuoi spazi salvati in un’unica lista.',
    searchRooms: 'Cerca stanze',
    noRooms: 'Nessuna stanza disponibile',
    noRoomsSaved: 'Le stanze che crei o a cui ti unisci su questo dispositivo resteranno qui fino alla fine.',
    noPublicRooms: 'Al momento non ci sono stanze pubbliche attive.',
    copyChat: 'Copia chat',
    roomControls: 'Controlli della stanza',
    peopleLabel: 'Persone',
    exitCharacter: 'Esci dal personaggio',
    createLabel: 'Crea stanza',
    joinLabel: 'Entra nella stanza',
    reconnectLabel: 'Riconnetti',
    roomDirectoryHeading: 'Chat',
    roomTitleLabel: 'Titolo stanza',
    roomTitleRequired: 'Aggiungi un nome prima di aprire la stanza.',
    roomCodeRequired: 'Inserisci un codice stanza.',
    roomCodeInvalid: 'Inserisci un codice stanza valido.',
    roomCodeLabel: 'Codice stanza',
    portraitLabel: 'Scegli la tua carta ritratto',
    roomTitlePlaceholder: 'Tetto dopo scuola',
    roomCodePlaceholder: 'ABCD-1234',
    messagePlaceholder: 'Messaggio...',
    createAction: 'Apri stanza',
    joinAction: 'Entra nella stanza',
    copyCode: 'Copia codice',
    refresh: 'Aggiorna',
    leaveView: 'Esci dalla vista',
    endRoom: 'Termina stanza',
    exitLabel: 'Esci dalla stanza',
    drawingBrush: 'Pennello',
    drawingEraser: 'Gomma',
    drawingFill: 'Riempi',
    drawingUndo: 'Annulla',
    drawingRedo: 'Ripristina',
    clearDrawing: 'Cancella',
    removeDrawing: 'Rimuovi',
    drawingDone: 'Fatto',
    tapToClear: 'Tocca {count}x',
    doneShort: 'Fatto!',
    doneLong: 'Ho finito!',
    fillCanvasConfirm: 'Riempire l’intera tela con il colore attuale?',
    roomCreatorLabel: 'Creatore della stanza',
    messageSideLabel: 'Lato messaggi (i tuoi messaggi)',
    messageSideRight: 'Destra (predefinito)',
    messageSideLeft: 'Sinistra (alternativa)',
    settingsLabel: 'Impostazioni',
    closeLabel: 'Chiudi',
    backLabel: 'Indietro',
    noSyncKey: 'Nessuna chiave di sincronizzazione',
    security: 'Sincronizzazione e identità',
    lobbyCreateHint: 'Configura la tua nuova stanza nella lobby...',
    lobbyJoinHint: 'Inserisci un codice per entrare in una stanza...',
    syncKeyHint: 'Questa chiave della scheda Progresso collega identità, scelte del personaggio e cronologia delle stanze su tutti i tuoi dispositivi.',
    syncKeyDetails: 'La scheda Sincronizzazione offre strumenti aggiuntivi per gestire la presenza cloud del tuo personaggio e la cronologia di lettura.',
    roomCodeCopyError: 'Impossibile copiare il codice stanza da questo browser.',
    roomChatCopyError: 'Impossibile copiare la chat della stanza da questo browser.',
    copiedRoomCodeStatus: '{roomId} copiato.',
    copiedRoomChatStatus: 'Chat copiata da {roomTitle}.',
    roomLiveStatus: 'La stanza {roomId} è attiva.',
    joinedRoomStatus: 'Entrato in {roomId}.',
    reconnectedRoomStatus: 'Riconnesso a {roomId}.',
    roomRefreshedStatus: 'La stanza {roomId} è stata aggiornata.',
    roomInactiveStatus: 'La stanza {roomId} non è più attiva.',
    identityReclaimed: 'Identità recuperata con successo!',
    failedToRedeemKey: 'Impossibile riscattare la chiave',
    unknownUser: 'Sconosciuto',
    roomDirectoryTab: 'Elenco stanze',
  },
};

export function getLocalizedChatCopy(uiLanguage = 'en') {
  return CHAT_COPY_BY_LANGUAGE[uiLanguage] || {};
}
