const COPY = {
  en: {
    menuTitle: 'Which animal are you?',
    menuDescription: 'A deeper instinct quiz for Satonosuke, Oshio, or Omiso.',
    introNote: 'A den-deep quiz that weighs warmth, caution, play, routine, and roaming instinct.',
    resultTitle: 'Your animal match',
    notesTitle: 'Animal reading',
    traitsTitle: 'Instinct traits',
    rankingTitle: 'Animal ranking',
    calculating: 'Reading your animal pattern...',
    certaintyLabel: 'Certainty',
    reliabilityIndexLabel: 'Reliability index',
    integrityScoreLabel: 'Integrity score',
    consistencyLabel: 'Instinct consistency',
    runnerUpLabel: 'Runner up',
    exploratoryNote: 'This match is best read as a live pattern, not a fixed label.',
    coherenceLabel: 'Coherence',
    extremeRateLabel: 'Extreme rate',
    recoveryRoundsLabel: 'Recovery rounds',
    dailyPredictionLabel: 'Daily prediction',
    contributionTitle: 'Contribution breakdown',
    contributionTotalLabel: 'total',
    retakeLabel: 'Retake quiz',
    balancedMiddle: 'balanced middle',
    predictionFallback: 'A quiet animal mood follows you today.',
    reasonFallbacks: {
      opener: 'Your animal pattern came through clearly.',
      anchor: 'Your answers formed a readable instinct pattern.',
      growth: 'Keep noticing what helps you feel safe, alive, and honest in motion.',
    },
    contributionLabels: {
      'axis fit': 'Axis fit',
      'factor fit': 'Factor fit',
      alignment: 'Pattern alignment',
      'top-factor overlap': 'Top-factor overlap',
      'profile balance': 'Profile balance',
      'reliability adj': 'Reliability bonus',
      'response penalty': 'Response penalty',
    },
    tierLabels: { high: 'High', clear: 'Clear', balanced: 'Balanced', quiet: 'Quiet' },
    clueLead: 'A clear clue came from {label}.',
    reliabilityContext: {
      exploratory: 'Treat this as a strong live read that could sharpen further with steadier answers over time.',
      stable: 'The pattern is fairly stable and holds together well across different question styles.',
      consistent: 'The pattern stays remarkably consistent even as the quiz changes format and pressure.',
    },
    factorLines: {
      chaosCharm: 'You lighten tension by introducing warmth, motion, or ridiculous little jolts of life.',
      watchCircle: 'You keep tracking subtle shifts long after other people decide the room is already settled.',
      denSoftness: 'Comfort is not optional for you; it is what lets your system trust the environment again.',
      soloRoam: 'You need enough private range to come back honestly instead of performing closeness on demand.',
      ritualAnchor: 'Repeated habits and familiar sequences quietly matter to you more than you may openly admit.',
      bounceEnergy: 'When you rebound, you tend to create movement again rather than sitting inside heaviness for long.',
    },
    traitLabels: {
      chaosCharm: 'Chaos charm',
      watchCircle: 'Watch circle',
      denSoftness: 'Den softness',
      soloRoam: 'Solo roam',
      ritualAnchor: 'Ritual anchor',
      bounceEnergy: 'Bounce energy',
    },
    traitDescriptions: {
      chaosCharm: { high: 'bright, disarming energy that turns tension into play', low: 'more measured than chaotic, with energy released carefully' },
      watchCircle: { high: 'quietly reading the room and keeping track of everything', low: 'relaxing fast instead of staying in guard mode' },
      denSoftness: { high: 'deeply soothed by comfort, familiarity, and gentle closeness', low: 'less tied to cozy predictability and more open to movement' },
      soloRoam: { high: 'needs space, range, and a little self-directed wandering', low: 'prefers staying closer to trusted people and known rhythms' },
      ritualAnchor: { high: 'stabilized by repeated habits, safe routes, and familiar timing', low: 'more willing to loosen routine and adapt in motion' },
      bounceEnergy: { high: 'quick to pop back up and create movement around others', low: 'recharges more quietly and spends energy carefully' },
    },
    profiles: {
      Satonosuke: {
        openers: [
          'Your pattern lands on Satonosuke energy: affectionate, goofy, and impossible to ignore once you feel safe.',
          'This reads Satonosuke: warm-hearted chaos with a genuine instinct to brighten the room around you.',
          'You matched Satonosuke because your responses kept pointing toward playful warmth over guarded distance.',
        ],
        anchor: 'You tend to reconnect through closeness, silliness, and immediate emotional lift.',
        growth: 'Your best rhythm comes from keeping that joy while respecting when your energy actually needs recovery.',
      },
      Oshio: {
        openers: [
          'Your result leans Oshio: quiet, exacting, and always a beat ahead of what the room is doing.',
          'This pattern is strongly Oshio: observant, self-directed, and far more alert than you first let on.',
          'You matched Oshio because your answers consistently favored watchfulness, pattern-reading, and guarded range.',
        ],
        anchor: 'You seem to trust your own read first, then move once the terrain actually makes sense.',
        growth: 'You stay strongest when you let curiosity lead without turning every unknown into a threat signal.',
      },
      Omiso: {
        openers: [
          'Your result settles on Omiso energy: comforting, soft, and quietly grounding for everyone nearby.',
          'This looks very Omiso: cozy, affectionate, and steady in a way that lowers the temperature of the room.',
          'You matched Omiso because your pattern keeps choosing softness, safety, and reliable warmth over noise.',
        ],
        anchor: 'You regulate best through comfort, familiar pacing, and a calm kind of closeness.',
        growth: 'Things stay healthiest when rest is a source of strength, not a reason to disappear from what matters.',
      },
    },
  },
  es: {
    menuTitle: 'Que animal eres?',
    menuDescription: 'Un quiz mas profundo para Satonosuke, Oshio u Omiso.',
    introNote: 'Un quiz profundo que pesa calidez, cautela, juego, rutina e instinto de movimiento.',
    resultTitle: 'Tu animal',
    notesTitle: 'Lectura animal',
    traitsTitle: 'Rasgos instintivos',
    rankingTitle: 'Ranking animal',
    calculating: 'Leyendo tu patron animal...',
    certaintyLabel: 'Certeza',
    reliabilityIndexLabel: 'Indice de fiabilidad',
    integrityScoreLabel: 'Puntaje de integridad',
    consistencyLabel: 'Consistencia instintiva',
    runnerUpLabel: 'Segundo puesto',
    exploratoryNote: 'Este resultado se lee mejor como un patron vivo, no como una etiqueta fija.',
    coherenceLabel: 'Coherencia',
    extremeRateLabel: 'Tasa extrema',
    recoveryRoundsLabel: 'Rondas de ajuste',
    dailyPredictionLabel: 'Prediccion diaria',
    contributionTitle: 'Desglose de contribucion',
    contributionTotalLabel: 'total',
    retakeLabel: 'Repetir quiz',
    balancedMiddle: 'punto medio',
    predictionFallback: 'Hoy te sigue un humor animal tranquilo.',
    reasonFallbacks: {
      opener: 'Tu patron animal aparecio con claridad.',
      anchor: 'Tus respuestas formaron un patron instintivo facil de leer.',
      growth: 'Sigue notando lo que te ayuda a sentirte seguro, vivo y honesto en movimiento.',
    },
    contributionLabels: {
      'axis fit': 'Ajuste de ejes',
      'factor fit': 'Ajuste de factores',
      alignment: 'Alineacion del patron',
      'top-factor overlap': 'Coincidencia de factores clave',
      'profile balance': 'Balance del perfil',
      'reliability adj': 'Bono de fiabilidad',
      'response penalty': 'Penalizacion de respuesta',
    },
    tierLabels: { high: 'Alta', clear: 'Clara', balanced: 'Balanceada', quiet: 'Suave' },
    clueLead: 'Una pista clara vino de {label}.',
    reliabilityContext: {
      exploratory: 'Tomalo como una lectura fuerte del momento que puede afinarse con respuestas mas estables.',
      stable: 'El patron es bastante estable y se sostiene bien entre distintos tipos de preguntas.',
      consistent: 'El patron se mantiene muy consistente incluso cuando cambia el formato y la presion del quiz.',
    },
    factorLines: {
      chaosCharm: 'Suavizas la tension introduciendo calidez, movimiento o pequenas chispas de vida.',
      watchCircle: 'Sigues rastreando cambios sutiles mucho despues de que otros dan la sala por resuelta.',
      denSoftness: 'La comodidad no es opcional para ti; es lo que permite que tu sistema vuelva a confiar.',
      soloRoam: 'Necesitas suficiente espacio privado para volver con honestidad y no desde la actuacion.',
      ritualAnchor: 'Los habitos repetidos y las secuencias conocidas importan en silencio mas de lo que admites.',
      bounceEnergy: 'Cuando te recuperas, sueles volver a crear movimiento en lugar de quedarte dentro del peso.',
    },
    traitLabels: {
      chaosCharm: 'Encanto caotico',
      watchCircle: 'Circulo vigilante',
      denSoftness: 'Suavidad de guarida',
      soloRoam: 'Paseo en solitario',
      ritualAnchor: 'Ancla ritual',
      bounceEnergy: 'Energia de rebote',
    },
    traitDescriptions: {
      chaosCharm: { high: 'energia brillante y desarmante que convierte la tension en juego', low: 'una energia mas medida que caotica, liberada con cuidado' },
      watchCircle: { high: 'lees la sala en silencio y llevas la cuenta de todo', low: 'te relajas rapido en vez de quedarte en guardia' },
      denSoftness: { high: 'te calma profundamente la comodidad, lo familiar y la cercania suave', low: 'dependes menos de la comodidad predecible y aceptas mejor el movimiento' },
      soloRoam: { high: 'necesitas espacio, margen y un poco de exploracion propia', low: 'prefieres quedarte cerca de personas de confianza y ritmos conocidos' },
      ritualAnchor: { high: 'te estabilizan los habitos repetidos, las rutas seguras y los tiempos familiares', low: 'te resulta mas facil aflojar la rutina y adaptarte en movimiento' },
      bounceEnergy: { high: 'vuelves a levantarte rapido y generas movimiento alrededor de otros', low: 'te recargas con mas silencio y gastas la energia con cuidado' },
    },
    profiles: {
      Satonosuke: {
        openers: [
          'Tu patron cae en energia Satonosuke: carinoso, torpe y imposible de ignorar cuando te sientes a salvo.',
          'Esto se lee como Satonosuke: caos de buen corazon con un instinto real de alegrar la sala.',
          'Coincidiste con Satonosuke porque tus respuestas seguian apuntando a la calidez juguetona por encima de la distancia defensiva.',
        ],
        anchor: 'Sueles reconectar a traves de la cercania, la tonteria y un alivio emocional inmediato.',
        growth: 'Tu mejor ritmo aparece cuando conservas esa alegria sin ignorar cuando tu energia necesita recuperarse.',
      },
      Oshio: {
        openers: [
          'Tu resultado se inclina hacia Oshio: silencioso, preciso y siempre un paso por delante de la sala.',
          'Este patron es muy Oshio: observador, autodirigido y mucho mas alerta de lo que muestras al principio.',
          'Coincidiste con Oshio porque tus respuestas favorecieron la vigilancia, la lectura de patrones y la distancia protegida.',
        ],
        anchor: 'Parece que primero confias en tu propia lectura y luego te mueves cuando el terreno ya tiene sentido.',
        growth: 'Te mantienes mas fuerte cuando dejas que la curiosidad guie sin convertir cada desconocido en una amenaza.',
      },
      Omiso: {
        openers: [
          'Tu resultado se asienta en energia Omiso: reconfortante, suave y discretamente estabilizadora para quienes te rodean.',
          'Esto se ve muy Omiso: acogedor, afectuoso y constante de una manera que baja la temperatura de la sala.',
          'Coincidiste con Omiso porque tu patron sigue eligiendo suavidad, seguridad y calidez confiable por encima del ruido.',
        ],
        anchor: 'Te regulas mejor a traves del confort, un ritmo familiar y una cercania tranquila.',
        growth: 'Todo se mantiene mas sano cuando el descanso es una fuente de fuerza y no una razon para desaparecer de lo que importa.',
      },
    },
  },
  pt: {
    menuTitle: 'Qual animal voce e?',
    menuDescription: 'Um quiz mais profundo para Satonosuke, Oshio ou Omiso.',
    introNote: 'Um quiz profundo que pesa calor, cautela, brincadeira, rotina e instinto de andar.',
    resultTitle: 'Seu animal',
    notesTitle: 'Leitura animal',
    traitsTitle: 'Tracos instintivos',
    rankingTitle: 'Ranking animal',
    calculating: 'Lendo seu padrao animal...',
    certaintyLabel: 'Certeza',
    reliabilityIndexLabel: 'Indice de confiabilidade',
    integrityScoreLabel: 'Pontuacao de integridade',
    consistencyLabel: 'Consistencia instintiva',
    runnerUpLabel: 'Segundo lugar',
    exploratoryNote: 'Este resultado funciona melhor como um padrao vivo, nao como um rotulo fixo.',
    coherenceLabel: 'Coerencia',
    extremeRateLabel: 'Taxa extrema',
    recoveryRoundsLabel: 'Rodadas de ajuste',
    dailyPredictionLabel: 'Previsao diaria',
    contributionTitle: 'Detalhamento da contribuicao',
    contributionTotalLabel: 'total',
    retakeLabel: 'Fazer de novo',
    balancedMiddle: 'meio equilibrado',
    predictionFallback: 'Um humor animal tranquilo acompanha voce hoje.',
    reasonFallbacks: {
      opener: 'Seu padrao animal apareceu com clareza.',
      anchor: 'Suas respostas formaram um padrao instintivo facil de ler.',
      growth: 'Continue percebendo o que ajuda voce a se sentir seguro, vivo e honesto em movimento.',
    },
    contributionLabels: {
      'axis fit': 'Ajuste de eixos',
      'factor fit': 'Ajuste de fatores',
      alignment: 'Alinhamento do padrao',
      'top-factor overlap': 'Coincidencia de fatores centrais',
      'profile balance': 'Balanceamento do perfil',
      'reliability adj': 'Bonus de confiabilidade',
      'response penalty': 'Penalidade de resposta',
    },
    tierLabels: { high: 'Alta', clear: 'Clara', balanced: 'Equilibrada', quiet: 'Calma' },
    clueLead: 'Um sinal claro veio de {label}.',
    reliabilityContext: {
      exploratory: 'Leia isto como uma leitura forte do momento que pode ficar mais nitida com respostas mais estaveis.',
      stable: 'O padrao esta bem estavel e se sustenta entre estilos diferentes de pergunta.',
      consistent: 'O padrao permanece muito consistente mesmo quando o formato e a pressao mudam.',
    },
    factorLines: {
      chaosCharm: 'Voce alivia a tensao trazendo calor, movimento ou pequenas centelhas de vida.',
      watchCircle: 'Voce continua rastreando mudancas sutis muito depois de os outros acharem que a sala ja assentou.',
      denSoftness: 'Conforto nao e opcional para voce; e o que permite que seu sistema volte a confiar no ambiente.',
      soloRoam: 'Voce precisa de alcance privado suficiente para voltar com honestidade em vez de atuar proximidade.',
      ritualAnchor: 'Habitos repetidos e sequencias familiares importam em silencio mais do que voce costuma admitir.',
      bounceEnergy: 'Quando se recupera, voce tende a recriar movimento em vez de ficar parado dentro do peso.',
    },
    traitLabels: {
      chaosCharm: 'Charme caotico',
      watchCircle: 'Circulo de vigia',
      denSoftness: 'Maciez de toca',
      soloRoam: 'Andar sozinho',
      ritualAnchor: 'Ancora ritual',
      bounceEnergy: 'Energia de retorno',
    },
    traitDescriptions: {
      chaosCharm: { high: 'energia brilhante e desarmante que transforma tensao em brincadeira', low: 'energia mais medida do que caotica, solta com cuidado' },
      watchCircle: { high: 'le o ambiente em silencio e acompanha tudo', low: 'relaxa rapido em vez de permanecer em modo de guarda' },
      denSoftness: { high: 'e profundamente acalmado por conforto, familiaridade e proximidade gentil', low: 'fica menos preso ao aconchego previsivel e mais aberto ao movimento' },
      soloRoam: { high: 'precisa de espaco, alcance e um pouco de exploracao por conta propria', low: 'prefere ficar perto de pessoas confiaveis e ritmos conhecidos' },
      ritualAnchor: { high: 'e estabilizado por habitos repetidos, caminhos seguros e tempos familiares', low: 'aceita afrouxar a rotina e se adaptar em movimento com mais facilidade' },
      bounceEnergy: { high: 'volta rapido e cria movimento ao redor dos outros', low: 'recarrega de forma mais silenciosa e gasta energia com cuidado' },
    },
    profiles: {
      Satonosuke: {
        openers: [
          'Seu padrao cai em energia Satonosuke: afetuoso, baguncado e impossivel de ignorar quando voce se sente seguro.',
          'Isto soa como Satonosuke: caos de bom coracao com um impulso real de alegrar o ambiente.',
          'Voce combinou com Satonosuke porque suas respostas apontaram repetidamente para calor brincalhao acima da distancia defensiva.',
        ],
        anchor: 'Voce tende a se reconectar por proximidade, bobagem e alivio emocional imediato.',
        growth: 'Seu melhor ritmo aparece quando voce preserva essa alegria sem ignorar quando sua energia precisa de recuperacao.',
      },
      Oshio: {
        openers: [
          'Seu resultado puxa para Oshio: quieto, preciso e sempre um compasso a frente do ambiente.',
          'Este padrao e bem Oshio: observador, autodirigido e muito mais alerta do que parece no inicio.',
          'Voce combinou com Oshio porque suas respostas favoreceram vigilancia, leitura de padroes e distancia protegida.',
        ],
        anchor: 'Parece que voce confia primeiro na propria leitura e so depois se move quando o terreno realmente faz sentido.',
        growth: 'Voce fica mais forte quando deixa a curiosidade guiar sem transformar todo desconhecido em sinal de ameaca.',
      },
      Omiso: {
        openers: [
          'Seu resultado se acomoda em energia Omiso: acolhedora, macia e discretamente estabilizadora para quem esta por perto.',
          'Isto parece muito Omiso: aconchegante, afetuoso e constante de um jeito que abaixa a temperatura do ambiente.',
          'Voce combinou com Omiso porque seu padrao continua escolhendo suavidade, seguranca e calor confiavel acima do ruido.',
        ],
        anchor: 'Voce se regula melhor por conforto, ritmo familiar e uma proximidade calma.',
        growth: 'Tudo fica mais saudavel quando o descanso vira fonte de forca, nao motivo para sumir do que importa.',
      },
    },
  },
  fr: {
    menuTitle: 'Quel animal es-tu ?',
    menuDescription: 'Un quiz plus profond pour Satonosuke, Oshio ou Omiso.',
    introNote: 'Un quiz profond qui pese chaleur, prudence, jeu, routine et instinct de mouvement.',
    resultTitle: 'Ton animal',
    notesTitle: 'Lecture animale',
    traitsTitle: 'Traits instinctifs',
    rankingTitle: 'Classement animal',
    calculating: 'Lecture de ton motif animal...',
    certaintyLabel: 'Certitude',
    reliabilityIndexLabel: 'Indice de fiabilite',
    integrityScoreLabel: 'Score d integrite',
    consistencyLabel: 'Constance instinctive',
    runnerUpLabel: 'Second',
    exploratoryNote: 'Ce resultat se lit mieux comme un motif vivant, pas comme une etiquette fixe.',
    coherenceLabel: 'Coherence',
    extremeRateLabel: 'Taux extreme',
    recoveryRoundsLabel: 'Tours de recalage',
    dailyPredictionLabel: 'Prediction du jour',
    contributionTitle: 'Detail de la contribution',
    contributionTotalLabel: 'total',
    retakeLabel: 'Refaire le quiz',
    balancedMiddle: 'milieu equilibre',
    predictionFallback: 'Une humeur animale calme te suit aujourd hui.',
    reasonFallbacks: {
      opener: 'Ton motif animal est apparu clairement.',
      anchor: 'Tes reponses ont forme un schema instinctif facile a lire.',
      growth: 'Continue a remarquer ce qui t aide a te sentir en securite, vivant et sincere en mouvement.',
    },
    contributionLabels: {
      'axis fit': 'Ajustement des axes',
      'factor fit': 'Ajustement des facteurs',
      alignment: 'Alignement du schema',
      'top-factor overlap': 'Recouvrement des facteurs dominants',
      'profile balance': 'Equilibre du profil',
      'reliability adj': 'Bonus de fiabilite',
      'response penalty': 'Penalite de reponse',
    },
    tierLabels: { high: 'Fort', clear: 'Net', balanced: 'Equilibre', quiet: 'Calme' },
    clueLead: 'Un indice clair est venu de {label}.',
    reliabilityContext: {
      exploratory: 'Lis cela comme une lecture forte du moment qui peut devenir plus nette avec des reponses plus stables.',
      stable: 'Le motif reste assez stable et tient bien a travers differents styles de questions.',
      consistent: 'Le motif reste tres coherent meme quand le format et la pression changent.',
    },
    factorLines: {
      chaosCharm: 'Tu fais baisser la tension en apportant chaleur, mouvement ou petites etincelles de vie.',
      watchCircle: 'Tu continues a suivre les changements subtils longtemps apres que les autres pensent que la piece est deja retombee.',
      denSoftness: 'Le confort n est pas optionnel pour toi; c est ce qui permet a ton systeme de refaire confiance.',
      soloRoam: 'Tu as besoin d assez d espace prive pour revenir honnetement sans jouer la proximite.',
      ritualAnchor: 'Les habitudes repetees et les sequences familieres comptent en silence plus que tu ne l admets.',
      bounceEnergy: 'Quand tu rebondis, tu recrees du mouvement au lieu de rester longtemps dans la lourdeur.',
    },
    traitLabels: {
      chaosCharm: 'Charme chaotique',
      watchCircle: 'Cercle de veille',
      denSoftness: 'Douceur du refuge',
      soloRoam: 'Derive en solo',
      ritualAnchor: 'Ancre rituelle',
      bounceEnergy: 'Energie de rebond',
    },
    traitDescriptions: {
      chaosCharm: { high: 'une energie vive et desarmante qui transforme la tension en jeu', low: 'une energie plus mesuree que chaotique, liberee con soin' },
      watchCircle: { high: 'lit calmement la piece et garde la trace de tout', low: 'se detend vite au lieu de rester en garde' },
      denSoftness: { high: 'apaise profondement par le confort, le familier et une proximite douce', low: 'moins attache au cocon previsible et plus ouvert au mouvement' },
      soloRoam: { high: 'a besoin d espace, d amplitude et d un peu d errance autonome', low: 'prefere rester pres des personnes de confiance et des rythmes connus' },
      ritualAnchor: { high: 'stabilise par des habitudes repetees, des trajets surs et des tempos familiers', low: 'plus dispose a desserrer la routine et a s adapter en mouvement' },
      bounceEnergy: { high: 'repart vite et recree du mouvement autour des autres', low: 'se recharge plus calmement et depense son energie avec soin' },
    },
    profiles: {
      Satonosuke: {
        openers: [
          'Ton motif tombe sur une energie Satonosuke : affectueuse, maladroite et impossible a ignorer quand tu te sens en securite.',
          'Cela sonne Satonosuke : un chaos tendre avec un vrai instinct pour remettre de la vie dans la piece.',
          'Tu as matche Satonosuke parce que tes reponses pointaient sans cesse vers une chaleur joueuse plutot que vers la distance defensive.',
        ],
        anchor: 'Tu te reconnectes souvent par la proximite, le ridicule et un soulagement emotionnel immediat.',
        growth: 'Ton meilleur rythme apparait quand tu gardes cette joie sans ignorer le moment ou ton energie doit recuperer.',
      },
      Oshio: {
        openers: [
          'Ton resultat penche vers Oshio : discret, precis et toujours un temps d avance sur la piece.',
          'Ce motif est tres Oshio : observateur, autonome et beaucoup plus alerte qu il n y parait au debut.',
          'Tu as matche Oshio parce que tes reponses privilegient la vigilance, la lecture des motifs et une distance protegee.',
        ],
        anchor: 'On dirait que tu fais d abord confiance a ta propre lecture, puis tu bouges une fois que le terrain a vraiment du sens.',
        growth: 'Tu restes le plus solide quand tu laisses la curiosite guider sans transformer chaque inconnu en signal d alerte.',
      },
      Omiso: {
        openers: [
          'Ton resultat se pose sur une energie Omiso : reconfortante, douce et discretement stabilisatrice pour les autres.',
          'Cela ressemble beaucoup a Omiso : cosy, affectueux et regulier d une facon qui baisse la temperature de la piece.',
          'Tu as matche Omiso parce que ton motif choisit encore et encore la douceur, la securite et une chaleur fiable plutot que le bruit.',
        ],
        anchor: 'Tu te regules le mieux par le confort, un rythme familier et une proximite calme.',
        growth: 'Tout reste plus sain quand le repos devient une source de force plutot qu une raison de disparaitre de ce qui compte.',
      },
    },
  },
  de: {
    menuTitle: 'Welches Tier bist du?',
    menuDescription: 'Ein tieferes Instinkt Quiz fur Satonosuke, Oshio oder Omiso.',
    introNote: 'Ein tieferes Quiz zu Warme, Vorsicht, Spiel, Routine und Streif Instinkt.',
    resultTitle: 'Dein Tier',
    notesTitle: 'Tierlesung',
    traitsTitle: 'Instinktmerkmale',
    rankingTitle: 'Tier Ranking',
    calculating: 'Dein Tiermuster wird gelesen...',
    certaintyLabel: 'Sicherheit',
    reliabilityIndexLabel: 'Zuverlassigkeitsindex',
    integrityScoreLabel: 'Integritatswert',
    consistencyLabel: 'Instinkt Konsistenz',
    runnerUpLabel: 'Zweiter Platz',
    exploratoryNote: 'Dieses Ergebnis liest man besser als lebendiges Muster, nicht als starres Etikett.',
    coherenceLabel: 'Koharenz',
    extremeRateLabel: 'Extremrate',
    recoveryRoundsLabel: 'Kalibrierungsrunden',
    dailyPredictionLabel: 'Tagesprognose',
    contributionTitle: 'Beitragsaufschluesselung',
    contributionTotalLabel: 'gesamt',
    retakeLabel: 'Quiz neu starten',
    balancedMiddle: 'ausgewogene Mitte',
    predictionFallback: 'Heute begleitet dich eine ruhige Tierstimmung.',
    reasonFallbacks: {
      opener: 'Dein Tiermuster ist klar hervorgetreten.',
      anchor: 'Deine Antworten haben ein gut lesbares Instinktmuster ergeben.',
      growth: 'Achte weiter darauf, was dir hilft, dich sicher, lebendig und ehrlich in Bewegung zu fuehlen.',
    },
    contributionLabels: {
      'axis fit': 'Achsen-Passung',
      'factor fit': 'Faktoren-Passung',
      alignment: 'Muster-Ausrichtung',
      'top-factor overlap': 'Ueberschneidung der Hauptfaktoren',
      'profile balance': 'Profil-Balance',
      'reliability adj': 'Zuverlaessigkeitsbonus',
      'response penalty': 'Antwortabzug',
    },
    tierLabels: { high: 'Hoch', clear: 'Klar', balanced: 'Ausgewogen', quiet: 'Leise' },
    clueLead: 'Ein klarer Hinweis kam von {label}.',
    reliabilityContext: {
      exploratory: 'Lies das als starke Momentaufnahme, die mit ruhigeren Antworten noch schaerfer werden kann.',
      stable: 'Das Muster ist ziemlich stabil und haelt auch zwischen verschiedenen Fragetypen gut zusammen.',
      consistent: 'Das Muster bleibt bemerkenswert konsistent, selbst wenn Format und Druck wechseln.',
    },
    factorLines: {
      chaosCharm: 'Du loest Spannung, indem du Waerme, Bewegung oder kleine absurde Funken von Leben hineinbringst.',
      watchCircle: 'Du verfolgst feine Veraenderungen noch lange, nachdem andere den Raum schon fuer beruhigt halten.',
      denSoftness: 'Komfort ist fuer dich nicht optional; dadurch kann dein System der Umgebung wieder vertrauen.',
      soloRoam: 'Du brauchst genug privaten Spielraum, um ehrlich zurueckzukommen statt Naehe nur zu spielen.',
      ritualAnchor: 'Wiederholte Gewohnheiten und vertraute Abfolgen bedeuten dir still mehr, als du offen zugibst.',
      bounceEnergy: 'Wenn du dich erholst, erzeugst du eher wieder Bewegung, statt lange in der Schwere sitzen zu bleiben.',
    },
    traitLabels: {
      chaosCharm: 'Chaos Charme',
      watchCircle: 'Wach Kreis',
      denSoftness: 'Nest Weichheit',
      soloRoam: 'Allein Streifen',
      ritualAnchor: 'Ritual Anker',
      bounceEnergy: 'Rueckfeder Energie',
    },
    traitDescriptions: {
      chaosCharm: { high: 'helle, entwaffnende Energie, die Spannung in Spiel verwandelt', low: 'mehr bedacht als chaotisch, mit vorsichtig freigesetzter Energie' },
      watchCircle: { high: 'liest den Raum still und behaelt alles im Blick', low: 'entspannt sich schnell, statt im Wachmodus zu bleiben' },
      denSoftness: { high: 'wird tief durch Komfort, Vertrautheit und sanfte Naehe beruhigt', low: 'ist weniger an vorhersehbare Gemuetlichkeit gebunden und offener fuer Bewegung' },
      soloRoam: { high: 'braucht Raum, Reichweite und ein wenig selbstbestimmtes Umherschweifen', low: 'bleibt lieber naeher bei vertrauten Menschen und bekannten Rhythmen' },
      ritualAnchor: { high: 'wird durch wiederholte Gewohnheiten, sichere Wege und vertrautes Timing stabilisiert', low: 'lockert Routinen leichter und passt sich in Bewegung an' },
      bounceEnergy: { high: 'springt schnell wieder auf und erzeugt Bewegung um andere herum', low: 'laedt ruhiger auf und setzt Energie sorgfaeltig ein' },
    },
    profiles: {
      Satonosuke: {
        openers: [
          'Dein Muster landet bei Satonosuke Energie: liebevoll, albern und kaum zu uebersehen, sobald du dich sicher fuehlst.',
          'Das liest sich nach Satonosuke: warmherziges Chaos mit echtem Instinkt, den Raum aufzuhellen.',
          'Du passt zu Satonosuke, weil deine Antworten immer wieder auf spielerische Waerme statt auf defensive Distanz gezeigt haben.',
        ],
        anchor: 'Du findest meist ueber Naehe, Albernheit und sofortige emotionale Erleichterung wieder Anschluss.',
        growth: 'Dein bester Rhythmus entsteht, wenn du diese Freude behaeltst und zugleich merkst, wann deine Energie Erholung braucht.',
      },
      Oshio: {
        openers: [
          'Dein Ergebnis zieht Richtung Oshio: leise, praezise und dem Raum immer einen Schlag voraus.',
          'Dieses Muster ist deutlich Oshio: beobachtend, selbstgesteuert und viel wachsamer, als du zuerst wirkst.',
          'Du passt zu Oshio, weil deine Antworten Wachsamkeit, Musterlesen und geschuetzten Abstand bevorzugt haben.',
        ],
        anchor: 'Es wirkt so, als vertraust du zuerst deiner eigenen Einschaetzung und bewegst dich erst, wenn das Gelaende wirklich Sinn ergibt.',
        growth: 'Du bleibst am staerksten, wenn Neugier fuehren darf, ohne dass jedes Unbekannte gleich ein Warnsignal wird.',
      },
      Omiso: {
        openers: [
          'Dein Ergebnis setzt sich auf Omiso Energie: troestend, weich und fuer andere leise stabilisierend.',
          'Das wirkt sehr nach Omiso: gemuetlich, zugewandt und bestaendig auf eine Weise, die den Raum herunterkuehlt.',
          'Du passt zu Omiso, weil dein Muster immer wieder Weichheit, Sicherheit und verlaessliche Waerme ueber Laerm waehlt.',
        ],
        anchor: 'Du regulierst dich am besten ueber Komfort, vertrautes Tempo und eine ruhige Form von Naehe.',
        growth: 'Am gesuendesten bleibt es, wenn Ruhe eine Quelle von Kraft ist und kein Grund, dich von Wichtigem abzusetzen.',
      },
    },
  },
  it: {
    menuTitle: 'Che animale sei?',
    menuDescription: 'Un quiz piu profondo per Satonosuke, Oshio o Omiso.',
    introNote: 'Un quiz profondo che pesa calore, cautela, gioco, routine e istinto di movimento.',
    resultTitle: 'Il tuo animale',
    notesTitle: 'Lettura animale',
    traitsTitle: 'Tratti istintivi',
    rankingTitle: 'Classifica animale',
    calculating: 'Sto leggendo il tuo schema animale...',
    certaintyLabel: 'Certezza',
    reliabilityIndexLabel: 'Indice di affidabilita',
    integrityScoreLabel: 'Punteggio di integrita',
    consistencyLabel: 'Consistenza istintiva',
    runnerUpLabel: 'Secondo posto',
    exploratoryNote: 'Questo risultato si legge meglio come schema vivo, non come etichetta fissa.',
    coherenceLabel: 'Coerenza',
    extremeRateLabel: 'Tasso estremo',
    recoveryRoundsLabel: 'Round di recupero',
    dailyPredictionLabel: 'Previsione del giorno',
    contributionTitle: 'Dettaglio del contributo',
    contributionTotalLabel: 'totale',
    retakeLabel: 'Rifai il quiz',
    balancedMiddle: 'mezzo equilibrato',
    predictionFallback: 'Oggi ti accompagna un umore animale tranquillo.',
    reasonFallbacks: {
      opener: 'Il tuo schema animale e emerso con chiarezza.',
      anchor: 'Le tue risposte hanno formato un modello istintivo leggibile.',
      growth: 'Continua a notare cio che ti aiuta a sentirti al sicuro, vivo e sincero nel movimento.',
    },
    contributionLabels: {
      'axis fit': 'Aderenza degli assi',
      'factor fit': 'Aderenza dei fattori',
      alignment: 'Allineamento del modello',
      'top-factor overlap': 'Sovrapposizione dei fattori principali',
      'profile balance': 'Bilanciamento del profilo',
      'reliability adj': 'Bonus di affidabilita',
      'response penalty': 'Penalita di risposta',
    },
    tierLabels: { high: 'Alta', clear: 'Chiara', balanced: 'Bilanciata', quiet: 'Quieta' },
    clueLead: 'Un indizio chiaro e arrivato da {label}.',
    reliabilityContext: {
      exploratory: 'Leggilo come una lettura forte del momento che puo affinarsi con risposte piu stabili.',
      stable: 'Il profilo e abbastanza stabile e tiene bene tra stili di domanda diversi.',
      consistent: 'Il profilo resta notevolmente coerente anche quando cambiano formato e pressione.',
    },
    factorLines: {
      chaosCharm: 'Alleggerisci la tensione portando calore, movimento o piccole scariche di vita.',
      watchCircle: 'Continui a seguire i cambiamenti sottili molto dopo che gli altri credono che la stanza si sia gia assestata.',
      denSoftness: 'Il comfort per te non e opzionale; e cio che permette al tuo sistema di tornare a fidarsi.',
      soloRoam: 'Hai bisogno di abbastanza spazio privato per tornare in modo onesto invece di recitare vicinanza.',
      ritualAnchor: 'Abitudini ripetute e sequenze familiari contano in silenzio piu di quanto ammetti apertamente.',
      bounceEnergy: 'Quando ti riprendi, tendi a ricreare movimento invece di restare a lungo dentro la pesantezza.',
    },
    traitLabels: {
      chaosCharm: 'Fascino caotico',
      watchCircle: 'Cerchio di guardia',
      denSoftness: 'Morbidezza della tana',
      soloRoam: 'Vagare da solo',
      ritualAnchor: 'Ancora rituale',
      bounceEnergy: 'Energia di rimbalzo',
    },
    traitDescriptions: {
      chaosCharm: { high: 'energia luminosa e disarmante che trasforma la tensione in gioco', low: 'energia piu misurata che caotica, rilasciata con cura' },
      watchCircle: { high: 'legge la stanza in silenzio e tiene traccia di tutto', low: 'si rilassa in fretta invece di restare in guardia' },
      denSoftness: { high: 'e profondamente calmato da comfort, familiarita e vicinanza gentile', low: 'e meno legato alla comodita prevedibile e piu aperto al movimento' },
      soloRoam: { high: 'ha bisogno di spazio, raggio e un po di esplorazione autonoma', low: 'preferisce restare vicino a persone fidate e ritmi conosciuti' },
      ritualAnchor: { high: 'si stabilizza con abitudini ripetute, percorsi sicuri e tempi familiari', low: 'lascia andare piu facilmente la routine e si adatta in movimento' },
      bounceEnergy: { high: 'si rialza in fretta e crea movimento attorno agli altri', low: 'si ricarica piu in silenzio e spende energia con attenzione' },
    },
    profiles: {
      Satonosuke: {
        openers: [
          'Il tuo schema cade su energia Satonosuke: affettuosa, goffa e impossibile da ignorare quando ti senti al sicuro.',
          'Questo suona Satonosuke: caos di buon cuore con un vero istinto a ravvivare la stanza.',
          'Hai combaciato con Satonosuke perche le tue risposte continuavano a puntare verso calore giocoso piu che distanza difensiva.',
        ],
        anchor: 'Tendi a riconnetterti tramite vicinanza, sciocchezza e sollievo emotivo immediato.',
        growth: 'Il tuo ritmo migliore arriva quando conservi quella gioia senza ignorare il momento in cui la tua energia ha bisogno di recupero.',
      },
      Oshio: {
        openers: [
          'Il tuo risultato pende verso Oshio: silenzioso, preciso e sempre un battito avanti alla stanza.',
          'Questo schema e molto Oshio: osservatore, autodiretto e molto piu allerta di quanto mostri all inizio.',
          'Hai combaciato con Oshio perche le tue risposte favorivano vigilanza, lettura degli schemi e distanza protetta.',
        ],
        anchor: 'Sembra che tu ti fidi prima della tua lettura e poi ti muova quando il terreno ha davvero senso.',
        growth: 'Resti piu forte quando lasci guidare la curiosita senza trasformare ogni ignoto in un segnale di minaccia.',
      },
      Omiso: {
        openers: [
          'Il tuo risultato si posa su energia Omiso: confortante, morbida e discretamente stabilizzante per chi ti sta vicino.',
          'Questo sembra molto Omiso: accogliente, affettuoso e costante in un modo che abbassa la temperatura della stanza.',
          'Hai combaciato con Omiso perche il tuo schema continua a scegliere morbidezza, sicurezza e calore affidabile sopra il rumore.',
        ],
        anchor: 'Ti regoli meglio attraverso comfort, ritmo familiare e una vicinanza calma.',
        growth: 'Tutto resta piu sano quando il riposo e una fonte di forza e non una ragione per sparire da cio che conta.',
      },
    },
  },
};

export const getAnimalQuizCopy = (uiLanguage = 'en', t = {}) => ({
  ...(COPY[uiLanguage] || COPY.en),
  menuTitle: t?.mystery?.whichAnimal || (COPY[uiLanguage] || COPY.en).menuTitle,
  menuDescription: t?.mystery?.whichAnimalDesc || (COPY[uiLanguage] || COPY.en).menuDescription,
});

export default getAnimalQuizCopy;
