import { QUOTES } from '../../data/quotes';

const findQuote = (needle) => QUOTES.find((quote) => quote.author.toLowerCase().includes(needle.toLowerCase())) || null;

export const WIKI_ENTRY_EXTRAS = {
  'characters:mitsumi-iwakura': {
    tags: ['Protagonist', 'Ishikawa', 'Student council', 'Tokyo', 'Growth'],
    quote: findQuote('mitsumi'),
    highlights: [
      { label: 'Trajectory', value: 'Rural honors student adjusting to Tokyo while keeping a concrete public-service dream.' },
      { label: 'Core tension', value: 'Earnest confidence in long-term goals paired with everyday social and urban friction.' },
      { label: 'Story function', value: 'Acts as the stabilizing center who makes other characters reveal themselves more honestly.' },
    ],
    relationshipGraph: {
      centerId: 'mitsumi',
      nodes: [
        {
          id: 'mitsumi',
          label: 'Mitsumi',
          shortLabel: 'Self',
          accent: '#2563eb',
          x: 50,
          y: 50,
          summary: 'Mitsumi anchors the cast through directness, ambition, and emotional openness.',
          detail: 'Most of her key relationships work because other characters react to how unusually sincere and goal-oriented she is.',
        },
        {
          id: 'shima',
          label: 'Shima',
          accent: '#f97316',
          x: 80,
          y: 26,
          relation: 'Mutual recognition',
          summary: 'Shima is drawn to Mitsumi because she moves through life without the performance habits he relies on.',
          detail: 'Their dynamic mixes affection, admiration, and a sense that each exposes a missing part of the other.',
          articleRef: { categoryId: 'characters', entryId: 'sousuke-shima' },
        },
        {
          id: 'nao',
          label: 'Nao',
          accent: '#8b5cf6',
          x: 22,
          y: 24,
          relation: 'Guardian support',
          summary: 'Nao gives Mitsumi safety, practical advice, and a place where she can recalibrate.',
          detail: 'This relationship grounds the story in adulthood and belonging rather than limiting Mitsumi to school life alone.',
          articleRef: { categoryId: 'characters', entryId: 'nao' },
        },
        {
          id: 'mika',
          label: 'Mika',
          accent: '#ef4444',
          x: 23,
          y: 76,
          relation: 'Growth through friction',
          summary: 'Mika’s insecurity sharpens around Mitsumi, then gradually turns into a more honest friendship.',
          detail: 'Mitsumi does not fix Mika, but her steadiness helps Mika confront comparison, envy, and self-worth more clearly.',
          articleRef: { categoryId: 'characters', entryId: 'mika-egashira' },
        },
        {
          id: 'yuzuki',
          label: 'Yuzuki',
          accent: '#14b8a6',
          x: 80,
          y: 74,
          relation: 'Social balance',
          summary: 'Yuzuki brings polish and observational calm to Mitsumi’s friend group.',
          detail: 'Their dynamic shows how Mitsumi’s blunt honesty can coexist with people who are much more strategic about presentation.',
          articleRef: { categoryId: 'characters', entryId: 'yuzuki-murashige' },
        },
      ],
      edges: [
        {
          id: 'mitsumi-shima',
          from: 'mitsumi',
          to: 'shima',
          label: 'Mutual pull',
          curve: -18,
          color: '#f97316',
          emotions: ['Admiration', 'Curiosity', 'Romantic tension'],
          intensity: 'High',
          status: 'Evolving',
          detail: 'This line mixes warmth and attraction with the discomfort of being changed by someone else.',
        },
        {
          id: 'mitsumi-nao',
          from: 'mitsumi',
          to: 'nao',
          label: 'Home base',
          curve: 18,
          color: '#8b5cf6',
          emotions: ['Safety', 'Trust', 'Guidance'],
          intensity: 'High',
          status: 'Stable',
          detail: 'Nao offers the kind of emotional and practical shelter that lets Mitsumi recover and process the city on her own terms.',
        },
        {
          id: 'mitsumi-mika',
          from: 'mitsumi',
          to: 'mika',
          label: 'Messy friendship',
          curve: -10,
          color: '#ef4444',
          emotions: ['Jealousy', 'Respect', 'Growth'],
          intensity: 'Medium',
          status: 'Improving',
          detail: 'The relationship begins with friction and comparison, then slowly turns into a more honest friendship.',
        },
        {
          id: 'mitsumi-yuzuki',
          from: 'mitsumi',
          to: 'yuzuki',
          label: 'Friend-group balance',
          curve: 12,
          color: '#14b8a6',
          emotions: ['Ease', 'Respect', 'Social comfort'],
          intensity: 'Medium',
          status: 'Supportive',
          detail: 'Yuzuki helps keep Mitsumi’s social world balanced by bringing calm and social perception into the group.',
        },
        {
          id: 'shima-mika',
          from: 'shima',
          to: 'mika',
          label: 'Misread desire',
          curve: 30,
          color: '#fb7185',
          emotions: ['Projection', 'Embarrassment', 'Distance'],
          intensity: 'Medium',
          status: 'Uneven',
          detail: 'Mika’s feelings toward Shima reveal how attraction, self-image, and class dynamics can become tangled.',
        },
        {
          id: 'yuzuki-mika',
          from: 'yuzuki',
          to: 'mika',
          label: 'Peer friction',
          curve: -28,
          color: '#06b6d4',
          emotions: ['Comparison', 'Solidarity', 'Adjustment'],
          intensity: 'Medium',
          status: 'Layered',
          detail: 'Their relationship carries moments of contrast and insecurity, but also the possibility of real peer recognition.',
        },
      ],
    },
    galleryVersions: [
      {
        id: 'portrait',
        label: 'Portrait',
        src: '/portrait/mitsumi.png',
        caption: 'Portrait image reused from the existing character assets.',
      },
      {
        id: 'character-art',
        label: 'Character art',
        src: '/characters/1c.png',
        caption: 'Existing Mitsumi character art used as an alternate reference view.',
      },
      {
        id: 'gallery-1',
        label: 'Gallery 1',
        src: '/gallery/characters/437666833_3850305738626583_8387245672677364761_n.jpg',
        caption: 'Existing gallery asset from the character collection.',
      },
      {
        id: 'gallery-2',
        label: 'Gallery 2',
        src: '/gallery/characters/437689246_3850305361959954_3062728486612005167_n.jpg',
        caption: 'Existing gallery asset from the character collection.',
      },
      {
        id: 'gallery-3',
        label: 'Gallery 3',
        src: '/gallery/characters/437712369_3850306258626531_8214326579282830286_n.jpg',
        caption: 'Existing gallery asset from the character collection.',
      },
      {
        id: 'gallery-4',
        label: 'Gallery 4',
        src: '/gallery/characters/437724599_3850305318626625_3573862224850342905_n.jpg',
        caption: 'Existing gallery asset from the character collection.',
      },
    ],
    galleryImages: [
      '/portrait/mitsumi.png',
      '/characters/1c.png',
      '/gallery/characters/437666833_3850305738626583_8387245672677364761_n.jpg',
      '/gallery/characters/437689246_3850305361959954_3062728486612005167_n.jpg',
      '/gallery/characters/437712369_3850306258626531_8214326579282830286_n.jpg',
      '/gallery/characters/437724599_3850305318626625_3573862224850342905_n.jpg',
    ],
    galleryTitle: 'Mitsumi gallery',
  },
  'characters:sousuke-shima': {
    tags: ['Main lead', 'Former child actor', 'Popular boy', 'Identity', 'Relationships'],
    quote: findQuote('shima'),
    highlights: [
      { label: 'Public image', value: 'Easygoing, charming, and socially fluent in almost any room.' },
      { label: 'Private pressure', value: 'Carries old performance habits and uncertainty about what he actually wants.' },
      { label: 'Story function', value: 'Turns the apparent school prince archetype into a study of adaptation and emotional drift.' },
    ],
    relationshipGraph: {
      centerId: 'shima',
      nodes: [
        {
          id: 'shima',
          label: 'Shima',
          shortLabel: 'Self',
          accent: '#f97316',
          x: 50,
          y: 50,
          summary: 'Shima sits at the intersection of charisma, self-editing, and an ongoing search for genuine desire.',
          detail: 'Most of his strongest relationships involve people who disrupt or decode the polished version of himself.',
        },
        {
          id: 'mitsumi',
          label: 'Mitsumi',
          accent: '#2563eb',
          x: 18,
          y: 26,
          relation: 'Restorative honesty',
          summary: 'Mitsumi’s directness offers Shima a model of living with less performance and more intent.',
          detail: 'She is not just a romantic interest; she is one of the few people who makes him feel both seen and unsettled in a productive way.',
          articleRef: { categoryId: 'characters', entryId: 'mitsumi-iwakura' },
        },
        {
          id: 'ririka',
          label: 'Ririka',
          accent: '#ec4899',
          x: 81,
          y: 24,
          relation: 'Shared history',
          summary: 'Ririka ties Shima back to performance, expectation, and the unresolved parts of his earlier life.',
          detail: 'Her presence tends to reactivate emotional habits and memories he would rather avoid or outgrow.',
        },
        {
          id: 'mukai',
          label: 'Mukai',
          accent: '#14b8a6',
          x: 79,
          y: 76,
          relation: 'Everyday friendship',
          summary: 'Mukai helps anchor Shima in ordinary school life instead of pure image management.',
          detail: 'This side of the network matters because it shows Shima’s easier, lighter social rhythm outside romantic tension.',
        },
        {
          id: 'mother',
          label: 'Family past',
          accent: '#8b5cf6',
          x: 20,
          y: 78,
          relation: 'Old pressure',
          summary: 'His family history shapes how quickly he turns himself into someone usable for other people.',
          detail: 'Even when unnamed in a scene, that pressure explains a lot of his distance, caution, and emotional fatigue.',
        },
      ],
      edges: [
        {
          id: 'shima-mitsumi',
          from: 'shima',
          to: 'mitsumi',
          label: 'Recognition',
          curve: -16,
          color: '#2563eb',
          emotions: ['Relief', 'Attraction', 'Admiration'],
          intensity: 'High',
          status: 'Deepening',
          detail: 'Shima is pulled toward Mitsumi because she makes him feel less trapped inside a performance.',
        },
        {
          id: 'shima-ririka',
          from: 'shima',
          to: 'ririka',
          label: 'Residual baggage',
          curve: 18,
          color: '#ec4899',
          emotions: ['History', 'Guilt', 'Defensiveness'],
          intensity: 'High',
          status: 'Unresolved',
          detail: 'Ririka embodies the older emotional pressures and habits Shima has not fully escaped.',
        },
        {
          id: 'shima-mukai',
          from: 'shima',
          to: 'mukai',
          label: 'Normalcy',
          curve: 14,
          color: '#14b8a6',
          emotions: ['Ease', 'Humor', 'Routine'],
          intensity: 'Medium',
          status: 'Steady',
          detail: 'Mukai represents the ordinary school-life rhythm that keeps Shima from being defined only by his past.',
        },
        {
          id: 'shima-mother',
          from: 'shima',
          to: 'mother',
          label: 'Pressure memory',
          curve: -18,
          color: '#8b5cf6',
          emotions: ['Pressure', 'Hesitation', 'Emotional fatigue'],
          intensity: 'High',
          status: 'Lingering',
          detail: 'This influence explains why Shima often responds to closeness by adapting instead of speaking plainly.',
        },
        {
          id: 'ririka-mother',
          from: 'ririka',
          to: 'mother',
          label: 'Old system',
          curve: 28,
          color: '#a855f7',
          emotions: ['Performance', 'Expectation', 'Control'],
          intensity: 'Medium',
          status: 'Structural',
          detail: 'These parts of Shima’s life connect through an older ecosystem of image, pressure, and adult expectation.',
        },
      ],
    },
    galleryVersions: [
      { id: 'portrait', label: 'Portrait', src: '/portrait/shima.png', caption: 'Portrait image from the existing character assets.' },
      { id: 'interview-1', label: 'Interview visual 1', src: '/blog/takamatsu-interview-news/4.jpg', caption: 'Existing blog visual used as a supporting variant.' },
      { id: 'interview-2', label: 'Interview visual 2', src: '/blog/takamatsu-interview-news/8.jpg', caption: 'Existing blog visual used as a supporting variant.' },
    ],
    galleryImages: [
      '/portrait/shima.png',
      '/blog/takamatsu-interview-news/4.jpg',
      '/blog/takamatsu-interview-news/8.jpg',
    ],
    galleryTitle: 'Shima references',
  },
  'characters:nao': {
    tags: ['Guardian', 'Stylist', 'Belonging', 'Identity', 'Tokyo'],
    quote: findQuote('nao'),
    highlights: [
      { label: 'Perspective', value: 'Adult viewpoint on safety, self-presentation, and chosen belonging.' },
      { label: 'Practical role', value: 'Gives Mitsumi a livable Tokyo base and steadier judgment when the city overwhelms her.' },
      { label: 'Theme weight', value: 'Deepens the story’s argument that place matters because of whether someone can breathe there.' },
    ],
    galleryImages: [
      '/portrait/nao.png',
      '/blog/takamatsu-interview-news/5.jpg',
      '/blog/takamatsu-interview-news/7.jpg',
    ],
    galleryTitle: 'Nao references',
  },
  'characters:mika-egashira': {
    tags: ['Classmate', 'Jealousy', 'Growth', 'Self-worth', 'Friend group'],
    quote: findQuote('egashira'),
    highlights: [
      { label: 'Emotional mode', value: 'Defensive, proud, and sensitive to hierarchy or comparison.' },
      { label: 'Arc pattern', value: 'Learns through embarrassment rather than clean, idealized breakthroughs.' },
      { label: 'Story function', value: 'Keeps the friend group emotionally honest by making insecurity visible.' },
    ],
    galleryImages: [
      '/portrait/mika.png',
      '/blog/takamatsu-interview-news/2.jpg',
    ],
    galleryTitle: 'Mika references',
  },
  'characters:yuzuki-murashige': {
    tags: ['Classmate', 'Popularity', 'Image', 'Friendship', 'Guarded'],
    quote: findQuote('yuzuki'),
    highlights: [
      { label: 'Social read', value: 'Beautiful and poised on the surface, but much more strategic and self-protective underneath.' },
      { label: 'Key concern', value: 'How attention and reputation distort normal friendship.' },
      { label: 'Story function', value: 'Adds calm social intelligence and image-awareness to the ensemble.' },
    ],
    galleryVersions: [
      { id: 'portrait', label: 'Portrait', src: '/portrait/yuzuki.png', caption: 'Portrait image from the existing character assets.' },
      { id: 'gallery-1', label: 'Gallery 1', src: '/gallery/characters/437736120_3850305471959943_2904409561394603457_n.jpg', caption: 'Existing gallery image for Yuzuki.' },
      { id: 'gallery-2', label: 'Gallery 2', src: '/gallery/characters/437739740_3850306035293220_480779216822615957_n.jpg', caption: 'Existing gallery image for Yuzuki.' },
    ],
    galleryImages: [
      '/portrait/yuzuki.png',
      '/gallery/characters/437736120_3850305471959943_2904409561394603457_n.jpg',
      '/gallery/characters/437739740_3850306035293220_480779216822615957_n.jpg',
    ],
    galleryTitle: 'Yuzuki references',
  },
  'story:series-overview': {
    tags: ['Overview', 'Premise', 'School life', 'Friendship', 'Coming of age'],
    quote: findQuote('mitsumi'),
    highlights: [
      { label: 'Premise frame', value: 'A country-to-city move that opens up friendship, romance, family, and identity threads.' },
      { label: 'Tone engine', value: 'Small social misreads and ordinary kindnesses create most of the emotional movement.' },
      { label: 'Ensemble strength', value: 'Supporting characters carry their own inner logic rather than orbiting the leads as props.' },
    ],
    galleryImages: [
      '/opengraph-image.jpg',
      '/blog/takamatsu-interview-news/1.jpg',
      '/blog/takamatsu-interview-news/3.jpg',
    ],
    galleryTitle: 'Series gallery',
  },
  'story:mitsumi-and-shima': {
    tags: ['Relationship', 'Romance', 'Friendship', 'Character growth'],
    quote: findQuote('shima'),
    highlights: [
      { label: 'Central tension', value: 'Direct purpose collides with polished uncertainty.' },
      { label: 'What makes it work', value: 'The bond keeps changing shape instead of locking into a single category too early.' },
      { label: 'Narrative use', value: 'Lets the series explore recognition, pacing, and emotional ambiguity without losing warmth.' },
    ],
    relationshipGraph: {
      centerId: 'pair',
      nodes: [
        {
          id: 'pair',
          label: 'Mitsumi + Shima',
          shortLabel: 'Pair',
          accent: '#ea580c',
          x: 50,
          y: 50,
          summary: 'Their relationship works because it can carry romance, admiration, confusion, and mutual growth at once.',
          detail: 'The pair never feels static; each turning point changes how the connection should be understood.',
        },
        {
          id: 'mitsumi',
          label: 'Mitsumi',
          accent: '#2563eb',
          x: 18,
          y: 25,
          relation: 'Clarity',
          summary: 'Mitsumi brings momentum, honesty, and a clear sense of direction into the bond.',
          detail: 'Her value in the relationship is not passivity or rescue, but the force of someone who knows what she wants from life.',
          articleRef: { categoryId: 'characters', entryId: 'mitsumi-iwakura' },
        },
        {
          id: 'shima',
          label: 'Shima',
          accent: '#f97316',
          x: 82,
          y: 25,
          relation: 'Sensitivity',
          summary: 'Shima brings perception, gentleness, and a more unstable emotional history.',
          detail: 'He makes the relationship softer, but also more uncertain, because he is slower to define what he feels and wants.',
          articleRef: { categoryId: 'characters', entryId: 'sousuke-shima' },
        },
        {
          id: 'sekigahara',
          label: 'Sekigahara echo',
          accent: '#8b5cf6',
          x: 22,
          y: 78,
          relation: 'Origin idea',
          summary: 'The early conception drew from the appeal of a relationship built on recognizing someone’s flaws and still valuing them deeply.',
          detail: 'The direct historical scaffold faded, but the emotional logic remained in the pair’s dynamic.',
          articleRef: { categoryId: 'influences', entryId: 'sekigahara-parallels' },
        },
        {
          id: 'friend-group',
          label: 'Friend group',
          accent: '#14b8a6',
          x: 78,
          y: 78,
          relation: 'Social context',
          summary: 'Their bond is constantly shaped by classmates, routines, and the larger friend network around them.',
          detail: 'That context prevents the relationship from becoming sealed off or melodramatically isolated.',
        },
      ],
      edges: [
        {
          id: 'pair-mitsumi',
          from: 'pair',
          to: 'mitsumi',
          label: 'Purpose',
          curve: -16,
          color: '#2563eb',
          emotions: ['Clarity', 'Momentum', 'Earnestness'],
          intensity: 'High',
          status: 'Core force',
          detail: 'Mitsumi keeps the bond from collapsing into passive yearning by always bringing concrete direction and honesty.',
        },
        {
          id: 'pair-shima',
          from: 'pair',
          to: 'shima',
          label: 'Perception',
          curve: 16,
          color: '#f97316',
          emotions: ['Sensitivity', 'Ambivalence', 'Care'],
          intensity: 'High',
          status: 'Shifting',
          detail: 'Shima makes the relationship emotionally supple, but also harder to categorize and resolve.',
        },
        {
          id: 'pair-sekigahara',
          from: 'pair',
          to: 'sekigahara',
          label: 'Influence',
          curve: -14,
          color: '#8b5cf6',
          emotions: ['Recognition', 'Loyalty', 'Interpretation'],
          intensity: 'Medium',
          status: 'Origin echo',
          detail: 'The pair inherits the emotional logic of seeing someone’s difficult traits clearly and valuing them anyway.',
        },
        {
          id: 'pair-friend-group',
          from: 'pair',
          to: 'friend-group',
          label: 'Context',
          curve: 12,
          color: '#14b8a6',
          emotions: ['Observation', 'Pressure', 'Support'],
          intensity: 'Medium',
          status: 'Ongoing',
          detail: 'The wider cast keeps the relationship grounded in ordinary school rhythms instead of pure dramatic isolation.',
        },
        {
          id: 'mitsumi-shima-direct',
          from: 'mitsumi',
          to: 'shima',
          label: 'Direct bond',
          curve: 28,
          color: '#fb923c',
          emotions: ['Attraction', 'Mutual growth', 'Nervousness'],
          intensity: 'High',
          status: 'Mutual',
          detail: 'Their direct line carries the strongest emotional volatility because both people keep changing through contact with each other.',
        },
      ],
      legend: [
        { label: 'Warmth / attraction', color: '#fb923c' },
        { label: 'Trust / support', color: '#14b8a6' },
        { label: 'Pressure / old wounds', color: '#8b5cf6' },
        { label: 'Conflict / projection', color: '#ef4444' },
      ],
    },
    galleryImages: [
      '/opengraph-image.jpg',
      '/blog/takamatsu-interview-news/4.jpg',
      '/blog/takamatsu-interview-news/6.jpg',
    ],
    galleryTitle: 'Relationship references',
  },
  'influences:takamatsu-interview': {
    tags: ['Interview', 'Author notes', 'Creation process', 'Genre'],
    quote: findQuote('mitsumi'),
    highlights: [
      { label: 'Creation focus', value: 'Build characters vivid enough that even ordinary scenes carry weight.' },
      { label: 'Genre framing', value: 'Uses shojo emotional elasticity inside a seinen publication structure.' },
      { label: 'Reader aim', value: 'Offer companionship and encouragement without erasing grief or complexity.' },
    ],
    galleryImages: [
      '/blog/takamatsu-interview-news/1.jpg',
      '/blog/takamatsu-interview-news/2.jpg',
      '/blog/takamatsu-interview-news/3.jpg',
      '/blog/takamatsu-interview-news/4.jpg',
    ],
    galleryTitle: 'Interview visuals',
  },
  'story:manga': {
    tags: ['Manga', 'Serialization', 'Kodansha', 'Monthly Afternoon', 'Volumes'],
    galleryImages: [
      '/opengraph-image.jpg',
      '/blog/takamatsu-interview-news/1.jpg',
      '/blog/takamatsu-interview-news/3.jpg',
    ],
    galleryTitle: 'Manga references',
  },
  'story:manga-releases': {
    tags: ['ISBN', 'Volumes', 'Bibliography', 'Release dates'],
    galleryImages: [
      '/opengraph-image.jpg',
      '/blog/takamatsu-interview-news/3.jpg',
    ],
    galleryTitle: 'Release references',
  },
  'story:anime': {
    tags: ['Anime', 'P.A.WORKS', 'Season 1', 'Season 2', 'Broadcast'],
    galleryImages: [
      '/opengraph-image.jpg',
      '/blog/takamatsu-interview-news/4.jpg',
      '/blog/takamatsu-interview-news/8.jpg',
    ],
    galleryTitle: 'Anime references',
  },
  'story:anime-episodes': {
    tags: ['Episodes', 'Episode guide', 'Air dates', 'Storyboard', 'Direction'],
    galleryImages: [
      '/blog/takamatsu-interview-news/4.jpg',
      '/blog/takamatsu-interview-news/8.jpg',
      '/opengraph-image.jpg',
    ],
    galleryTitle: 'Episode references',
  },
  'story:anime-production-team': {
    tags: ['Production', 'Staff', 'Committee', 'Music', 'Studio'],
    galleryImages: [
      '/blog/takamatsu-interview-news/1.jpg',
      '/blog/takamatsu-interview-news/2.jpg',
      '/blog/takamatsu-interview-news/4.jpg',
    ],
    galleryTitle: 'Production references',
  },
  'story:locations-and-models': {
    tags: ['Locations', 'Ishikawa', 'Suzu', 'Models', 'Setting'],
    galleryImages: [
      '/portrait/mitsumi.png',
      '/opengraph-image.jpg',
    ],
    galleryTitle: 'Location references',
  },
  'story:stage-musical': {
    tags: ['Stage musical', 'Theater', '2026', 'Adaptation'],
    galleryImages: [
      '/opengraph-image.jpg',
      '/blog/takamatsu-interview-news/6.jpg',
    ],
    galleryTitle: 'Stage adaptation references',
  },
};

export const getWikiEntryExtras = (categoryId, entryId) => WIKI_ENTRY_EXTRAS[`${categoryId}:${entryId}`] || null;
