export const UI_TEXT = {
  en: {
    header: 'Quiz challenge',
    questionsTab: 'Questions',
    leaderboardTab: 'Leaderboard',
    globalBoard: 'Global leaderboard',
    localBoard: 'Local leaderboard',
    boardSource: 'Source',
    historyTab: 'History',
    setupTitle: 'Ready to play?',
    setupSetTitle: 'Choose question set',
    setupDifficultyTitle: 'Choose difficulty mode',
    nameLabel: 'Name',
    namePlaceholder: 'Enter your name',
    modeLabel: 'Question mode',
    difficultyLabel: 'Difficulty',
    mode10: '10 Questions',
    mode25: '25 Questions',
    randomBell: 'Random',
    returnMenu: 'Return to menu',
    returnMenuConfirmTitle: 'Leave current quiz?',
    returnMenuConfirmBody: 'Your current run will be discarded and you will go back to setup.',
    stayQuiz: 'Stay',
    leaveQuiz: 'Leave',
    start: 'Start quiz',
    score: 'Score',
    question: 'Question',
    difficulty: 'Difficulty',
    timeLeft: 'Time left',
    nextUp: 'Next question...',
    correct: 'Correct',
    wrong: 'Wrong',
    timeout: 'Time up',
    finalScore: 'Final Score',
    playAgain: 'Play Again',
    noLeaderboard: 'No leaderboard entries yet.',
    historyTitle: 'Recent quiz history',
    noHistory: 'No quiz history yet.',
    historyDifficulty: 'Mode',
    historySet: 'Set',
    historyResult: 'Result',
    bestScore: 'Best',
    played: 'Played',
    points: 'pts',
    step: 'Step',
    quiz: 'Quiz',
    go: 'Go',
  },
  es: {
    header: 'Desafío quiz',
    questionsTab: 'Preguntas',
    leaderboardTab: 'Ranking',
    globalBoard: 'Ranking global',
    localBoard: 'Ranking local',
    boardSource: 'Fuente',
    historyTab: 'Historial',
    setupTitle: '¿Listo para jugar?',
    setupSetTitle: 'Elige cantidad',
    setupDifficultyTitle: 'Elige dificultad',
    nameLabel: 'Nombre',
    namePlaceholder: 'Escribe tu nombre',
    modeLabel: 'Modo',
    difficultyLabel: 'Dificultad',
    mode10: '10 preguntas',
    mode25: '25 preguntas',
    randomBell: 'Aleatorio',
    returnMenu: 'Volver al menú',
    returnMenuConfirmTitle: '¿Salir del quiz?',
    returnMenuConfirmBody: 'Se descartará tu intento actual y volverás al inicio.',
    stayQuiz: 'Seguir',
    leaveQuiz: 'Salir',
    start: 'Iniciar quiz',
    score: 'Puntaje',
    question: 'Pregunta',
    difficulty: 'Dificultad',
    timeLeft: 'Tiempo',
    nextUp: 'Siguiente pregunta...',
    correct: 'Correcto',
    wrong: 'Incorrecto',
    timeout: 'Tiempo agotado',
    finalScore: 'Puntaje final',
    playAgain: 'Jugar de nuevo',
    noLeaderboard: 'Aún no hay registros.',
    historyTitle: 'Historial reciente',
    noHistory: 'Sin historial todavía.',
    historyDifficulty: 'Modo',
    historySet: 'Set',
    historyResult: 'Resultado',
    bestScore: 'Mejor',
    played: 'Partidas',
    points: 'pts',
    step: 'Paso',
    quiz: 'Quiz',
    go: 'Ya',
  },
  pt: {
    header: 'Desafio quiz',
    questionsTab: 'Perguntas',
    leaderboardTab: 'Ranking',
    globalBoard: 'Ranking global',
    localBoard: 'Ranking local',
    boardSource: 'Fonte',
    historyTab: 'Histórico',
    setupTitle: 'Pronto para jogar?',
    setupSetTitle: 'Escolha a quantidade',
    setupDifficultyTitle: 'Escolha a dificuldade',
    nameLabel: 'Nome',
    namePlaceholder: 'Digite seu nome',
    modeLabel: 'Modo',
    difficultyLabel: 'Dificuldade',
    mode10: '10 perguntas',
    mode25: '25 perguntas',
    randomBell: 'Aleatório',
    returnMenu: 'Voltar ao menu',
    returnMenuConfirmTitle: 'Sair do quiz atual?',
    returnMenuConfirmBody: 'Sua partida atual será descartada e você voltará ao início.',
    stayQuiz: 'Ficar',
    leaveQuiz: 'Sair',
    start: 'Iniciar quiz',
    score: 'Pontos',
    question: 'Pergunta',
    difficulty: 'Dificuldade',
    timeLeft: 'Tempo',
    nextUp: 'Próxima pergunta...',
    correct: 'Correto',
    wrong: 'Errado',
    timeout: 'Tempo esgotado',
    finalScore: 'Pontuação final',
    playAgain: 'Jogar novamente',
    noLeaderboard: 'Ainda não há ranking.',
    historyTitle: 'Histórico recente',
    noHistory: 'Ainda sem histórico.',
    historyDifficulty: 'Modo',
    historySet: 'Set',
    historyResult: 'Resultado',
    bestScore: 'Melhor',
    played: 'Partidas',
    points: 'pts',
    step: 'Passo',
    quiz: 'Quiz',
    go: 'Ir',
  },
  fr: {
    header: 'Défi quiz',
    questionsTab: 'Questions',
    leaderboardTab: 'Classement',
    globalBoard: 'Classement global',
    localBoard: 'Classement local',
    boardSource: 'Source',
    historyTab: 'Historique',
    setupTitle: 'Prêt à jouer ?',
    setupSetTitle: 'Choisir le nombre',
    setupDifficultyTitle: 'Choisir la difficulté',
    nameLabel: 'Nom',
    namePlaceholder: 'Entrez votre nom',
    modeLabel: 'Mode',
    difficultyLabel: 'Difficulté',
    mode10: '10 questions',
    mode25: '25 questions',
    randomBell: 'Aléatoire',
    returnMenu: 'Retour au menu',
    returnMenuConfirmTitle: 'Quitter le quiz ?',
    returnMenuConfirmBody: 'Votre partie en cours sera perdue et vous reviendrez au début.',
    stayQuiz: 'Rester',
    leaveQuiz: 'Quitter',
    start: 'Lancer le quiz',
    score: 'Score',
    question: 'Question',
    difficulty: 'Difficulté',
    timeLeft: 'Temps',
    nextUp: 'Question suivante...',
    correct: 'Correct',
    wrong: 'Faux',
    timeout: 'Temps écoulé',
    finalScore: 'Score final',
    playAgain: 'Rejouer',
    noLeaderboard: 'Aucun score pour le moment.',
    historyTitle: 'Historique récent',
    noHistory: 'Pas encore d’historique.',
    historyDifficulty: 'Mode',
    historySet: 'Set',
    historyResult: 'Résultat',
    bestScore: 'Meilleur',
    played: 'Parties',
    points: 'pts',
    step: 'Étape',
    quiz: 'Quiz',
    go: 'Go',
  },
  de: {
    header: 'Quiz-challenge',
    questionsTab: 'Fragen',
    leaderboardTab: 'Rangliste',
    globalBoard: 'Globale Rangliste',
    localBoard: 'Lokale Rangliste',
    boardSource: 'Quelle',
    historyTab: 'Verlauf',
    setupTitle: 'Bereit zum Spielen?',
    setupSetTitle: 'Fragenanzahl wählen',
    setupDifficultyTitle: 'Schwierigkeit wählen',
    nameLabel: 'Name',
    namePlaceholder: 'Namen eingeben',
    modeLabel: 'Modus',
    difficultyLabel: 'Schwierigkeit',
    mode10: '10 Fragen',
    mode25: '25 Fragen',
    randomBell: 'Zufall',
    returnMenu: 'Zum Menü',
    returnMenuConfirmTitle: 'Aktuelles Quiz verlassen?',
    returnMenuConfirmBody: 'Dein aktueller Lauf wird verworfen und du gehst zurück zum Start.',
    stayQuiz: 'Bleiben',
    leaveQuiz: 'Verlassen',
    start: 'Quiz starten',
    score: 'Punkte',
    question: 'Frage',
    difficulty: 'Schwierigkeit',
    timeLeft: 'Zeit',
    nextUp: 'Nächste Frage...',
    correct: 'Richtig',
    wrong: 'Falsch',
    timeout: 'Zeit abgelaufen',
    finalScore: 'Endpunktzahl',
    playAgain: 'Nochmal spielen',
    noLeaderboard: 'Noch keine Einträge.',
    historyTitle: 'Letzte Spiele',
    noHistory: 'Noch kein Verlauf.',
    historyDifficulty: 'Modus',
    historySet: 'Set',
    historyResult: 'Ergebnis',
    bestScore: 'Best',
    played: 'Gespielt',
    points: 'Pkt',
    step: 'Schritt',
    quiz: 'Quiz',
    go: 'Los',
  },
  it: {
    header: 'Sfida quiz',
    questionsTab: 'Domande',
    leaderboardTab: 'Classifica',
    globalBoard: 'Classifica globale',
    localBoard: 'Classifica locale',
    boardSource: 'Fonte',
    historyTab: 'Cronologia',
    setupTitle: 'Pronto a giocare?',
    setupSetTitle: 'Scegli quantità',
    setupDifficultyTitle: 'Scegli difficoltà',
    nameLabel: 'Nome',
    namePlaceholder: 'Inserisci il tuo nome',
    modeLabel: 'Modalità',
    difficultyLabel: 'Difficoltà',
    mode10: '10 domande',
    mode25: '25 domande',
    randomBell: 'Casuale',
    returnMenu: 'Torna al menu',
    returnMenuConfirmTitle: 'Lasciare il quiz?',
    returnMenuConfirmBody: 'La partita attuale verrà annullata e tornerai alla schermata iniziale.',
    stayQuiz: 'Resta',
    leaveQuiz: 'Esci',
    start: 'Avvia quiz',
    score: 'Punteggio',
    question: 'Domanda',
    difficulty: 'Difficoltà',
    timeLeft: 'Tempo',
    nextUp: 'Prossima domanda...',
    correct: 'Corretto',
    wrong: 'Sbagliato',
    timeout: 'Tempo scaduto',
    finalScore: 'Punteggio finale',
    playAgain: 'Gioca ancora',
    noLeaderboard: 'Nessun punteggio per ora.',
    historyTitle: 'Cronologia recente',
    noHistory: 'Nessuna cronologia.',
    historyDifficulty: 'Modalità',
    historySet: 'Set',
    historyResult: 'Risultato',
    bestScore: 'Migliore',
    played: 'Partite',
    points: 'pt',
    step: 'Passaggio',
    quiz: 'Quiz',
    go: 'Via',
  },
};
