import { SUPPORTED_UI_LANGUAGES } from './uiLanguage';

export const APP_UI_TEXT = {
  en: {
    languageName: 'English',
    accessibility: 'Accessibility',
    accessibilityOptions: 'Accessibility options',
    shortcuts: 'Shortcuts',
    keyboardHelp: 'Keyboard help',
    skipToContent: 'Skip to content',
    returnToTop: 'Top',
    reduceMotion: 'Reduce motion',
    largeText: 'Larger text',
    largeControls: 'Bigger controls',
    highContrast: 'High contrast',
    readableSpacing: 'Readable spacing',
    underlineLinks: 'Underline links',
    reduceTransparency: 'Reduce transparency',
    simplifyVisuals: 'Simplify visuals',
    dimNonEssentialColors: 'Dim non-essential colors',
    colorVisionMode: 'Color vision mode',
    colorVisionOff: 'Off',
    colorVisionProtanopia: 'Protanopia',
    colorVisionDeuteranopia: 'Deuteranopia',
    colorVisionTritanopia: 'Tritanopia',
    colorVisionBlackWhite: 'Black & White',
    settings: 'Settings',
    language: 'Language',
    tip: 'Tip: use 1..8 to jump tabs quickly.',
    usage: 'Shortcut uses this session: ',
    shortcutsIntro: 'Use these shortcuts for faster navigation:',
    mainTabShortcut: 'Jump to a main tab',
    prevNextSubtab: 'Previous / next subtab',
    close: 'Close',
    openTabPrefix: 'Open',
    tabSuffix: 'tab',
    seriesTitle: 'Skip & Loafer',
    tabs: {
      home: { label: 'Home' },
      chapters: { label: 'Chapters' },
      gallery: { label: 'Gallery', mobileLabel: 'Gallery' },
      sign: { label: 'Sign', mobileLabel: 'Sign' },
      fanGallery: { label: 'Fan gallery', mobileLabel: 'Fan gallery' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Reading', mobileLabel: 'Reading' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Birthdays', mobileLabel: 'Birthdays' },
      mystery: { label: 'Mystery', mobileLabel: 'Mystery' },
    },
  },
  es: {
    languageName: 'Español',
    accessibility: 'Accesibilidad',
    accessibilityOptions: 'Opciones de accesibilidad',
    shortcuts: 'Atajos',
    keyboardHelp: 'Ayuda de teclado',
    skipToContent: 'Saltar al contenido',
    returnToTop: 'Arriba',
    reduceMotion: 'Reducir movimiento',
    largeText: 'Texto más grande',
    largeControls: 'Controles más grandes',
    highContrast: 'Alto contraste',
    readableSpacing: 'Espaciado legible',
    underlineLinks: 'Subrayar enlaces',
    reduceTransparency: 'Reducir transparencias',
    simplifyVisuals: 'Simplificar efectos visuales',
    dimNonEssentialColors: 'Atenuar colores no esenciales',
    colorVisionMode: 'Modo de visión de color',
    colorVisionOff: 'Desactivado',
    colorVisionProtanopia: 'Protanopia',
    colorVisionDeuteranopia: 'Deuteranopia',
    colorVisionTritanopia: 'Tritanopia',
    colorVisionBlackWhite: 'Blanco y negro',
    settings: 'Ajustes',
    language: 'Idioma',
    tip: 'Consejo: usa 1..8 para cambiar de pestaña.',
    usage: 'Usos de atajos en esta sesión: ',
    shortcutsIntro: 'Usa estos atajos para navegar más rápido:',
    mainTabShortcut: 'Ir a una pestaña principal',
    prevNextSubtab: 'Subpestaña anterior/siguiente',
    close: 'Cerrar',
    openTabPrefix: 'Abrir',
    tabSuffix: 'pestaña',
    tabs: {
      home: { label: 'Inicio' },
      chapters: { label: 'Capítulos' },
      gallery: { label: 'Galería', mobileLabel: 'Galería' },
      sign: { label: 'Firma', mobileLabel: 'Firma' },
      fanGallery: { label: 'Galería fan', mobileLabel: 'Galería fan' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Lectura', mobileLabel: 'Lectura' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Cumpleaños', mobileLabel: 'Cumpleaños' },
      mystery: { label: 'Misterio', mobileLabel: 'Misterio' },
    },
  },
  pt: {
    languageName: 'Português',
    accessibility: 'Acessibilidade',
    accessibilityOptions: 'Opções de acessibilidade',
    shortcuts: 'Atalhos',
    keyboardHelp: 'Ajuda de teclado',
    skipToContent: 'Ir para o conteúdo',
    returnToTop: 'Topo',
    reduceMotion: 'Reduzir movimento',
    largeText: 'Texto maior',
    largeControls: 'Controles maiores',
    highContrast: 'Alto contraste',
    readableSpacing: 'Espaçamento legível',
    underlineLinks: 'Sublinhar links',
    reduceTransparency: 'Reduzir transparências',
    simplifyVisuals: 'Simplificar visuais',
    dimNonEssentialColors: 'Suavizar cores não essenciais',
    colorVisionMode: 'Modo de visão de cores',
    colorVisionOff: 'Desativado',
    colorVisionProtanopia: 'Protanopia',
    colorVisionDeuteranopia: 'Deuteranopia',
    colorVisionTritanopia: 'Tritanopia',
    colorVisionBlackWhite: 'Preto e branco',
    settings: 'Ajustes',
    language: 'Idioma',
    tip: 'Dica: use 1..8 para trocar de aba.',
    usage: 'Usos de atajos nesta sessão: ',
    shortcutsIntro: 'Use estes atalhos para navegar mais rápido:',
    mainTabShortcut: 'Ir para uma aba principal',
    prevNextSubtab: 'Subaba anterior/próxima',
    close: 'Fechar',
    openTabPrefix: 'Abrir',
    tabSuffix: 'aba',
    tabs: {
      home: { label: 'Início' },
      chapters: { label: 'Capítulos' },
      gallery: { label: 'Galeria', mobileLabel: 'Galeria' },
      sign: { label: 'Assinar', mobileLabel: 'Assinar' },
      fanGallery: { label: 'Galeria fan', mobileLabel: 'Galeria fan' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Leitura', mobileLabel: 'Leitura' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Aniversários', mobileLabel: 'Aniversários' },
      mystery: { label: 'Mistério', mobileLabel: 'Mistério' },
    },
  },
  fr: {
    languageName: 'Français',
    accessibility: 'Accessibilité',
    accessibilityOptions: 'Options d\'accessibilité',
    shortcuts: 'Raccourcis',
    keyboardHelp: 'Aide au clavier',
    skipToContent: 'Passer au contenu',
    returnToTop: 'Retour en haut',
    reduceMotion: 'Réduire les mouvements',
    largeText: 'Texte plus grand',
    largeControls: 'Contrôles plus grands',
    highContrast: 'Contraste élevé',
    readableSpacing: 'Espacement lisible',
    underlineLinks: 'Souligner les liens',
    reduceTransparency: 'Réduire la transparence',
    simplifyVisuals: 'Simplifier les visuels',
    dimNonEssentialColors: 'Atténuer les couleurs non essentielles',
    colorVisionMode: 'Mode de vision des couleurs',
    colorVisionOff: 'Désactivé',
    colorVisionProtanopia: 'Protanopie',
    colorVisionDeuteranopia: 'Deutéranopie',
    colorVisionTritanopia: 'Tritanopie',
    colorVisionBlackWhite: 'Noir et blanc',
    settings: 'Paramètres',
    language: 'Langue',
    tip: 'Astuce : utilisez 1..8 pour changer d\'onglet.',
    usage: 'Utilisations des raccourcis dans cette session : ',
    shortcutsIntro: 'Utilisez ces raccourcis pour naviguer plus rapidement :',
    mainTabShortcut: 'Aller à un onglet principal',
    prevNextSubtab: 'Sous-onglet précédent/suivant',
    close: 'Fermer',
    openTabPrefix: 'Ouvrir l\'onglet',
    tabSuffix: '',
    tabs: {
      home: { label: 'Accueil' },
      chapters: { label: 'Chapitres' },
      gallery: { label: 'Galerie', mobileLabel: 'Galerie' },
      sign: { label: 'Signer', mobileLabel: 'Signer' },
      fanGallery: { label: 'Galerie fan', mobileLabel: 'Galerie fan' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Lecture', mobileLabel: 'Lecture' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Anniversaires', mobileLabel: 'Anniv.' },
      mystery: { label: 'Mystère', mobileLabel: 'Mystère' },
    },
  },
  de: {
    languageName: 'Deutsch',
    accessibility: 'Barrierefreiheit',
    accessibilityOptions: 'Optionen für Barrierefreiheit',
    shortcuts: 'Tastenkombinationen',
    keyboardHelp: 'Tastaturhilfe',
    skipToContent: 'Zum Inhalt springen',
    returnToTop: 'Nach oben',
    reduceMotion: 'Animationen reduzieren',
    largeText: 'Größerer Text',
    largeControls: 'Größere Bedienelemente',
    highContrast: 'Hoher Kontrast',
    readableSpacing: 'Lesbarer Abstand',
    underlineLinks: 'Links unterstreichen',
    reduceTransparency: 'Transparenz reduzieren',
    simplifyVisuals: 'Visuelle Effekte vereinfachen',
    dimNonEssentialColors: 'Unwichtige Farben dimmen',
    colorVisionMode: 'Farbfehlsichtigkeits-Modus',
    colorVisionOff: 'Aus',
    colorVisionProtanopia: 'Protanopie',
    colorVisionDeuteranopia: 'Deuteranopie',
    colorVisionTritanopia: 'Tritanopie',
    colorVisionBlackWhite: 'Schwarz-Weiß',
    settings: 'Einstellungen',
    language: 'Sprache',
    tip: 'Tipp: Verwende 1..8, um den Tab zu wechseln.',
    usage: 'Verwendung von Tastenkombinationen in dieser Sitzung: ',
    shortcutsIntro: 'Verwende diese Tastenkombinationen, um schneller zu navigieren:',
    mainTabShortcut: 'Zu einem Haupt-Tab springen',
    prevNextSubtab: 'Vorheriger/nächster Unter-Tab',
    close: 'Schließen',
    openTabPrefix: 'Öffne',
    tabSuffix: 'Tab',
    tabs: {
      home: { label: 'Startseite' },
      chapters: { label: 'Kapitel' },
      gallery: { label: 'Galerie', mobileLabel: 'Galerie' },
      sign: { label: 'Signieren', mobileLabel: 'Signieren' },
      fanGallery: { label: 'Fan-Galerie', mobileLabel: 'Fan-Galerie' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Lesen', mobileLabel: 'Lesen' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Geburtstage', mobileLabel: 'Geburtstage' },
      mystery: { label: 'Mysterium', mobileLabel: 'Mysterium' },
    },
  },
  it: {
    languageName: 'Italiano',
    accessibility: 'Accessibilità',
    accessibilityOptions: 'Opzioni di accessibilità',
    shortcuts: 'Scorciatoie',
    keyboardHelp: 'Aiuto tastiera',
    skipToContent: 'Salta al contenuto',
    returnToTop: 'Torna su',
    reduceMotion: 'Riduci movimento',
    largeText: 'Testo più grande',
    largeControls: 'Controlli più grandi',
    highContrast: 'Alto contrasto',
    readableSpacing: 'Spaziatura leggibile',
    underlineLinks: 'Sottolinea link',
    reduceTransparency: 'Riduci trasparenza',
    simplifyVisuals: 'Semplifica effetti visivi',
    dimNonEssentialColors: 'Attenua colori non essenziali',
    colorVisionMode: 'Modalità visione dei colori',
    colorVisionOff: 'Disattivata',
    colorVisionProtanopia: 'Protanopia',
    colorVisionDeuteranopia: 'Deuteranopia',
    colorVisionTritanopia: 'Tritanopia',
    colorVisionBlackWhite: 'Bianco e nero',
    settings: 'Impostazioni',
    language: 'Lingua',
    tip: 'Suggerimento: usa 1..8 per cambiare scheda.',
    usage: 'Utilizzi scorciatoie in questa sessione: ',
    shortcutsIntro: 'Usa queste scorciatoie per navigare più velocemente:',
    mainTabShortcut: 'Vai a una scheda principale',
    prevNextSubtab: 'Scheda precedente/successiva',
    close: 'Chiudi',
    openTabPrefix: 'Apri',
    tabSuffix: 'scheda',
    tabs: {
      home: { label: 'Home' },
      chapters: { label: 'Capitoli' },
      gallery: { label: 'Galleria', mobileLabel: 'Galleria' },
      sign: { label: 'Firma', mobileLabel: 'Firma' },
      fanGallery: { label: 'Galleria fan', mobileLabel: 'Galleria fan' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Lettura', mobileLabel: 'Lettura' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Compleanni', mobileLabel: 'Compleanni' },
      mystery: { label: 'Mistero', mobileLabel: 'Mistero' },
    },
  },
  ja: {
    languageName: '日本語',
    accessibility: 'アクセシビリティ',
    accessibilityOptions: 'アクセシビリティ設定',
    shortcuts: 'ショートカット',
    keyboardHelp: 'キーボードヘルプ',
    skipToContent: '本文へスキップ',
    returnToTop: '上へ',
    reduceMotion: '動きを減らす',
    largeText: '文字を大きく',
    largeControls: 'ボタンを大きく',
    highContrast: '高コントラスト',
    readableSpacing: '読みやすい間隔',
    underlineLinks: 'リンクに下線',
    reduceTransparency: '透明度を下げる',
    simplifyVisuals: '見た目を簡素化',
    dimNonEssentialColors: '不要な色を抑える',
    colorVisionMode: '色覚モード',
    colorVisionOff: 'オフ',
    colorVisionProtanopia: '1型色覚',
    colorVisionDeuteranopia: '2型色覚',
    colorVisionTritanopia: '3型色覚',
    colorVisionBlackWhite: '白黒',
    settings: '設定',
    language: '言語',
    tip: 'ヒント: 1..8でタブをすばやく切り替えられます。',
    usage: 'このセッションで使ったショートカット: ',
    shortcutsIntro: 'より速く移動するために、次のショートカットを使えます:',
    mainTabShortcut: 'メインタブへ移動',
    prevNextSubtab: '前後のサブタブ',
    close: '閉じる',
    openTabPrefix: '開く',
    tabSuffix: 'タブ',
    seriesTitle: 'スキップとローファー',
    tabs: {
      home: { label: 'ホーム' },
      chapters: { label: '話数' },
      gallery: { label: 'ギャラリー', mobileLabel: 'ギャラリー' },
      sign: { label: 'サイン', mobileLabel: 'サイン' },
      fanGallery: { label: 'ファンギャラリー', mobileLabel: 'ファンギャラリー' },
      blog: { label: 'ブログ', mobileLabel: 'ブログ' },
      sync: { label: '読書', mobileLabel: '読書' },
      quiz: { label: 'クイズ', mobileLabel: 'クイズ' },
      birthdays: { label: '誕生日', mobileLabel: '誕生日' },
      mystery: { label: 'ミステリー', mobileLabel: 'ミステリー' },
    },
  },
};

export const APP_LANGUAGE_OPTIONS = SUPPORTED_UI_LANGUAGES.map((code) => ({
  code,
  name: APP_UI_TEXT[code]?.languageName || code,
}));

export default APP_UI_TEXT;
