export const UI_TEXT = {
  en: {
    languageName: 'English',
    accessibility: 'Accessibility',
    accessibilityOptions: 'Accessibility options',
    shortcuts: 'Shortcuts',
    keyboardHelp: 'Keyboard help',
    skipToContent: 'Skip to content',
    returnToTop: 'Top',
    reduceMotion: 'Reduce motion',
    largeText: 'Larger text',
    largeControls: 'Bigger controls',
    highContrast: 'High contrast',
    readableSpacing: 'Readable spacing',
    underlineLinks: 'Underline links',
    reduceTransparency: 'Reduce transparency',
    simplifyVisuals: 'Simplify visuals',
    dimNonEssentialColors: 'Dim non-essential colors',
    colorVisionMode: 'Color vision mode',
    colorVisionOff: 'Off',
    colorVisionProtanopia: 'Protanopia',
    colorVisionDeuteranopia: 'Deuteranopia',
    colorVisionTritanopia: 'Tritanopia',
    colorVisionBlackWhite: 'Black & White',
    language: 'Language',
    tip: 'Tip: use 1..7 to jump tabs quickly.',
    usage: 'Shortcut uses this session: ',
    shortcutsIntro: 'Use these shortcuts for faster navigation:',
    mainTabShortcut: 'Jump to a main tab',
    prevNextSubtab: 'Previous / next subtab',
    close: 'Close',
    openTabPrefix: 'Open',
    tabSuffix: 'tab',
    preOrderVolume: 'Pre-order volume',
    tabs: {
      home: { label: 'Home' },
      chapters: { label: 'Chapters' },
      gallery: { label: 'Gallery', mobileLabel: 'Gallery' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Progress & Sync', mobileLabel: 'Sync' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Birthdays', mobileLabel: 'Birthdays' },
    },
  },
  es: {
    languageName: 'Español',
    accessibility: 'Accesibilidad',
    accessibilityOptions: 'Opciones de accesibilidad',
    shortcuts: 'Atajos',
    keyboardHelp: 'Ayuda de teclado',
    skipToContent: 'Saltar al contenido',
    returnToTop: 'Arriba',
    reduceMotion: 'Reducir movimiento',
    largeText: 'Texto más grande',
    largeControls: 'Controles más grandes',
    highContrast: 'Alto contraste',
    readableSpacing: 'Espaciado legible',
    underlineLinks: 'Subrayar enlaces',
    reduceTransparency: 'Reducir transparencias',
    simplifyVisuals: 'Simplificar efectos visuales',
    dimNonEssentialColors: 'Atenuar colores no esenciales',
    colorVisionMode: 'Modo de visión de color',
    colorVisionOff: 'Desactivado',
    colorVisionProtanopia: 'Protanopia',
    colorVisionDeuteranopia: 'Deuteranopia',
    colorVisionTritanopia: 'Tritanopia',
    colorVisionBlackWhite: 'Blanco y negro',
    language: 'Idioma',
    tip: 'Consejo: usa 1..7 para cambiar de pestaña.',
    usage: 'Usos de atajos en esta sesión: ',
    shortcutsIntro: 'Usa estos atajos para navegar más rápido:',
    mainTabShortcut: 'Ir a una pestaña principal',
    prevNextSubtab: 'Subpestaña anterior/siguiente',
    close: 'Cerrar',
    openTabPrefix: 'Abrir',
    tabSuffix: 'pestaña',
    preOrderVolume: 'Reservar volumen',
    tabs: {
      home: { label: 'Inicio' },
      chapters: { label: 'Capítulos' },
      gallery: { label: 'Galería', mobileLabel: 'Galería' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Progreso', mobileLabel: 'Sinc.' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Cumpleaños', mobileLabel: 'Cumpleaños' },
    },
  },
  pt: {
    languageName: 'Português',
    accessibility: 'Acessibilidade',
    accessibilityOptions: 'Opções de acessibilidade',
    shortcuts: 'Atalhos',
    keyboardHelp: 'Ajuda de teclado',
    skipToContent: 'Ir para o conteúdo',
    returnToTop: 'Topo',
    reduceMotion: 'Reduzir movimento',
    largeText: 'Texto maior',
    largeControls: 'Controles maiores',
    highContrast: 'Alto contraste',
    readableSpacing: 'Espaçamento legível',
    underlineLinks: 'Sublinhar links',
    reduceTransparency: 'Reduzir transparências',
    simplifyVisuals: 'Simplificar visuais',
    dimNonEssentialColors: 'Suavizar cores não essenciais',
    colorVisionMode: 'Modo de visão de cores',
    colorVisionOff: 'Desativado',
    colorVisionProtanopia: 'Protanopia',
    colorVisionDeuteranopia: 'Deuteranopia',
    colorVisionTritanopia: 'Tritanopia',
    colorVisionBlackWhite: 'Preto e branco',
    language: 'Idioma',
    tip: 'Dica: use 1..7 para trocar de aba.',
    usage: 'Usos de atalhos nesta sessão: ',
    shortcutsIntro: 'Use estes atalhos para navegar mais rápido:',
    mainTabShortcut: 'Ir para uma aba principal',
    prevNextSubtab: 'Subaba anterior/próxima',
    close: 'Fechar',
    openTabPrefix: 'Abrir',
    tabSuffix: 'aba',
    preOrderVolume: 'Pré-venda de volume',
    tabs: {
      home: { label: 'Início' },
      chapters: { label: 'Capítulos' },
      gallery: { label: 'Galeria', mobileLabel: 'Galeria' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Progresso', mobileLabel: 'Sync' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Aniversários', mobileLabel: 'Aniversários' },
    },
  },
  fr: {
    languageName: 'Français',
    accessibility: 'Accessibilité',
    accessibilityOptions: 'Options d’accessibilité',
    shortcuts: 'Raccourcis',
    keyboardHelp: 'Aide clavier',
    skipToContent: 'Aller au contenu',
    returnToTop: 'Haut',
    reduceMotion: 'Réduire les animations',
    largeText: 'Texte plus grand',
    largeControls: 'Commandes plus grandes',
    highContrast: 'Contraste élevé',
    readableSpacing: 'Espacement lisible',
    underlineLinks: 'Souligner les liens',
    reduceTransparency: 'Réduire les transparences',
    simplifyVisuals: 'Simplifier les effets visuels',
    dimNonEssentialColors: 'Atténuer les couleurs non essentielles',
    colorVisionMode: 'Mode de vision des couleurs',
    colorVisionOff: 'Désactivé',
    colorVisionProtanopia: 'Protanopie',
    colorVisionDeuteranopia: 'Deutéranopie',
    colorVisionTritanopia: 'Tritanopie',
    colorVisionBlackWhite: 'Noir et blanc',
    language: 'Langue',
    tip: 'Astuce : utilisez 1..7 pour changer d’onglet.',
    usage: 'Utilisations des raccourcis cette session : ',
    shortcutsIntro: 'Utilisez ces raccourcis pour naviguer plus vite :',
    mainTabShortcut: 'Aller à un onglet principal',
    prevNextSubtab: 'Sous-onglet précédent/suivant',
    close: 'Fermer',
    openTabPrefix: 'Ouvrir',
    tabSuffix: 'onglet',
    preOrderVolume: 'Précommander le volume',
    tabs: {
      home: { label: 'Accueil' },
      chapters: { label: 'Chapitres' },
      gallery: { label: 'Galerie', mobileLabel: 'Galerie' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Suivi', mobileLabel: 'Sync' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Anniversaires', mobileLabel: 'Anniversaires' },
    },
  },
  de: {
    languageName: 'Deutsch',
    accessibility: 'Barrierefreiheit',
    accessibilityOptions: 'Barrierefreiheitsoptionen',
    shortcuts: 'Kurzbefehle',
    keyboardHelp: 'Tastaturhilfe',
    skipToContent: 'Zum Inhalt springen',
    returnToTop: 'Nach oben',
    reduceMotion: 'Bewegung reduzieren',
    largeText: 'Größerer Text',
    largeControls: 'Größere Bedienelemente',
    highContrast: 'Hoher Kontrast',
    readableSpacing: 'Bessere Leseabstände',
    underlineLinks: 'Links unterstreichen',
    reduceTransparency: 'Transparenzen reduzieren',
    simplifyVisuals: 'Visuelle Effekte vereinfachen',
    dimNonEssentialColors: 'Nicht wesentliche Farben abschwächen',
    colorVisionMode: 'Farbsehmodus',
    colorVisionOff: 'Aus',
    colorVisionProtanopia: 'Protanopie',
    colorVisionDeuteranopia: 'Deuteranopie',
    colorVisionTritanopia: 'Tritanopie',
    colorVisionBlackWhite: 'Schwarz-Weiß',
    language: 'Sprache',
    tip: 'Tipp: Nutze 1..7 zum schnellen Wechseln der Tabs.',
    usage: 'Shortcut-Nutzungen in dieser Sitzung: ',
    shortcutsIntro: 'Nutze diese Kurzbefehle für schnellere Navigation:',
    mainTabShortcut: 'Zu einem Haupt-Tab springen',
    prevNextSubtab: 'Vorheriger/nächster Untertab',
    close: 'Schließen',
    openTabPrefix: 'Öffne',
    tabSuffix: 'Tab',
    preOrderVolume: 'Band vorbestellen',
    tabs: {
      home: { label: 'Start' },
      chapters: { label: 'Kapitel' },
      gallery: { label: 'Galerie', mobileLabel: 'Galerie' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Fortschr.' , mobileLabel: 'Sync' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Geburtstage', mobileLabel: 'Geburtstage' },
    },
  },
  it: {
    languageName: 'Italiano',
    accessibility: 'Accessibilità',
    accessibilityOptions: 'Opzioni di accessibilità',
    shortcuts: 'Scorciatoie',
    keyboardHelp: 'Guida tastiera',
    skipToContent: 'Vai al contenuto',
    returnToTop: 'Su',
    reduceMotion: 'Riduci movimento',
    largeText: 'Testo più grande',
    largeControls: 'Controlli più grandi',
    highContrast: 'Alto contrasto',
    readableSpacing: 'Spaziatura leggibile',
    underlineLinks: 'Sottolinea i link',
    reduceTransparency: 'Riduci trasparenze',
    simplifyVisuals: 'Semplifica effetti visivi',
    dimNonEssentialColors: 'Attenua i colori non essenziali',
    colorVisionMode: 'Modalità visione colori',
    colorVisionOff: 'Disattivato',
    colorVisionProtanopia: 'Protanopia',
    colorVisionDeuteranopia: 'Deuteranopia',
    colorVisionTritanopia: 'Tritanopia',
    colorVisionBlackWhite: 'Bianco e nero',
    language: 'Lingua',
    tip: 'Suggerimento: usa 1..7 per cambiare scheda rapidamente.',
    usage: 'Utilizzi scorciatoie in questa sessione: ',
    shortcutsIntro: 'Usa queste scorciatoie per navigare più velocemente:',
    mainTabShortcut: 'Vai a una scheda principale',
    prevNextSubtab: 'Sottoscheda precedente/successiva',
    close: 'Chiudi',
    openTabPrefix: 'Apri',
    tabSuffix: 'scheda',
    preOrderVolume: 'Preordina volume',
    tabs: {
      home: { label: 'Home' },
      chapters: { label: 'Capitoli' },
      gallery: { label: 'Galleria', mobileLabel: 'Galleria' },
      blog: { label: 'Blog', mobileLabel: 'Blog' },
      sync: { label: 'Progressi', mobileLabel: 'Sync' },
      quiz: { label: 'Quiz', mobileLabel: 'Quiz' },
      birthdays: { label: 'Compleanni', mobileLabel: 'Compleanni' },
    },
  },
};
