export const UI_TEXT = {
  en: {
    header: 'Quiz challenge',
    questionsTab: 'Questions',
    leaderboardTab: 'Leaderboard',
    globalBoard: 'Global leaderboard',
    localBoard: 'Local leaderboard',
    leaderboardHeading: 'Rankings',
    totalPlayersLabel: 'Total players',
    gamesPlayedLabel: 'Games played',
    historyHeading: 'Recent records',
    historyGlobalAttempts: 'Global attempts',
    historyTopRecord: 'Top record',
    historyScored: 'scored',
    historyPlayed: 'played',
    boardSource: 'Source',
    historyTab: 'History',
    setupTitle: 'Ready to play?',
    setupInstructions: '1. Enter your name. 2. Pick a difficulty. 3. Choose your question set.',
    setupSetTitle: 'Choose number of questions',
    setupDifficultyTitle: 'Choose difficulty mode',
    questionsSuffix: 'questions',
    difficultyEasy: 'Easy',
    difficultyMedium: 'Medium',
    difficultyHard: 'Hard',
    difficultyReallyHard: 'Really hard',
    difficultyRandom: 'Random',
    nameLabel: 'Name',
    namePlaceholder: 'Enter your name',
    nameRequired: 'Please enter your name before starting.',
    difficultyFirst: 'Choose difficulty first',
    modeLabel: 'Question mode',
    difficultyLabel: 'Difficulty',
    mode10: '10 Questions',
    mode25: '25 Questions',
    randomBell: 'Random',
    returnMenu: 'Return to menu',
    returnMenuConfirmTitle: 'Leave current quiz?',
    returnMenuConfirmBody: 'Your current run will be discarded and you will go back to setup.',
    stayQuiz: 'Stay',
    leaveQuiz: 'Leave',
    start: 'Start quiz',
    score: 'Score',
    question: 'Question',
    difficulty: 'Difficulty',
    timeLeft: 'Time left',
    nextUp: 'Next question...',
    correct: 'Correct',
    wrong: 'Wrong',
    timeout: 'Time up',
    finalScore: 'Final Score',
    playAgain: 'Play Again',
    noLeaderboard: 'No leaderboard entries yet.',
    historyTitle: 'Recent quiz history',
    noHistory: 'No quiz history yet.',
    historyDifficulty: 'Mode',
    historySet: 'Set',
    historyResult: 'Result',
    bestScore: 'Best',
    played: 'Played',
    points: 'pts',
    step: 'Step',
    quiz: 'Quiz',
    go: 'Go',
  },
  es: {
    header: 'Desafío quiz',
    questionsTab: 'Preguntas',
    leaderboardTab: 'Ranking',
    globalBoard: 'Ranking global',
    localBoard: 'Ranking local',
    leaderboardHeading: 'Clasificación',
    totalPlayersLabel: 'Jugadores totales',
    gamesPlayedLabel: 'Partidas jugadas',
    historyHeading: 'Registros recientes',
    historyGlobalAttempts: 'Intentos globales',
    historyTopRecord: 'Mejor marca',
    historyScored: 'anotó',
    historyPlayed: 'jugadas',
    boardSource: 'Fuente',
    historyTab: 'Historial',
    setupTitle: '¿Listo para jugar?',
    setupInstructions: '1. Escribe tu nombre. 2. Elige dificultad. 3. Elige el set de preguntas.',
    setupSetTitle: 'Elige número de preguntas',
    setupDifficultyTitle: 'Elige dificultad',
    questionsSuffix: 'preguntas',
    difficultyEasy: 'Fácil',
    difficultyMedium: 'Media',
    difficultyHard: 'Difícil',
    difficultyReallyHard: 'Muy difícil',
    difficultyRandom: 'Aleatorio',
    nameLabel: 'Nombre',
    namePlaceholder: 'Escribe tu nombre',
    nameRequired: 'Escribe tu nombre antes de empezar.',
    difficultyFirst: 'Elige la dificultad primero',
    modeLabel: 'Modo',
    difficultyLabel: 'Dificultad',
    mode10: '10 preguntas',
    mode25: '25 preguntas',
    randomBell: 'Aleatorio',
    returnMenu: 'Volver al menú',
    returnMenuConfirmTitle: '¿Salir del quiz?',
    returnMenuConfirmBody: 'Se descartará tu intento actual y volverás al inicio.',
    stayQuiz: 'Seguir',
    leaveQuiz: 'Salir',
    start: 'Iniciar quiz',
    score: 'Puntaje',
    question: 'Pregunta',
    difficulty: 'Dificultad',
    timeLeft: 'Tiempo',
    nextUp: 'Siguiente pregunta...',
    correct: 'Correcto',
    wrong: 'Incorrecto',
    timeout: 'Tiempo agotado',
    finalScore: 'Puntaje final',
    playAgain: 'Jugar de nuevo',
    noLeaderboard: 'Aún no hay registros.',
    historyTitle: 'Historial reciente',
    noHistory: 'Sin historial todavía.',
    historyDifficulty: 'Modo',
    historySet: 'Set',
    historyResult: 'Resultado',
    bestScore: 'Mejor',
    played: 'Partidas',
    points: 'pts',
    step: 'Paso',
    quiz: 'Quiz',
    go: 'Ya',
  },
  pt: {
    header: 'Desafio quiz',
    questionsTab: 'Perguntas',
    leaderboardTab: 'Ranking',
    globalBoard: 'Ranking global',
    localBoard: 'Ranking local',
    leaderboardHeading: 'Ranking',
    totalPlayersLabel: 'Jogadores totais',
    gamesPlayedLabel: 'Jogos jogados',
    historyHeading: 'Registos recentes',
    historyGlobalAttempts: 'Tentativas globais',
    historyTopRecord: 'Melhor marca',
    historyScored: 'marcou',
    historyPlayed: 'jogadas',
    boardSource: 'Fonte',
    historyTab: 'Histórico',
    setupTitle: 'Pronto para jogar?',
    setupInstructions: '1. Digite seu nome. 2. Escolha a dificuldade. 3. Escolha o conjunto de perguntas.',
    setupSetTitle: 'Escolha o número de perguntas',
    setupDifficultyTitle: 'Escolha a dificuldade',
    questionsSuffix: 'perguntas',
    difficultyEasy: 'Fácil',
    difficultyMedium: 'Média',
    difficultyHard: 'Difícil',
    difficultyReallyHard: 'Muito difícil',
    difficultyRandom: 'Aleatório',
    nameLabel: 'Nome',
    namePlaceholder: 'Digite seu nome',
    nameRequired: 'Digite seu nome antes de começar.',
    difficultyFirst: 'Escolha a dificuldade primeiro',
    modeLabel: 'Modo',
    difficultyLabel: 'Dificuldade',
    mode10: '10 perguntas',
    mode25: '25 perguntas',
    randomBell: 'Aleatório',
    returnMenu: 'Voltar ao menu',
    returnMenuConfirmTitle: 'Sair do quiz atual?',
    returnMenuConfirmBody: 'Sua partida atual será descartada e você voltará ao início.',
    stayQuiz: 'Ficar',
    leaveQuiz: 'Sair',
    start: 'Iniciar quiz',
    score: 'Pontos',
    question: 'Pergunta',
    difficulty: 'Dificuldade',
    timeLeft: 'Tempo',
    nextUp: 'Próxima pergunta...',
    correct: 'Correto',
    wrong: 'Errado',
    timeout: 'Tempo esgotado',
    finalScore: 'Pontuação final',
    playAgain: 'Jogar novamente',
    noLeaderboard: 'Ainda não há ranking.',
    historyTitle: 'Histórico recente',
    noHistory: 'Ainda sem histórico.',
    historyDifficulty: 'Modo',
    historySet: 'Set',
    historyResult: 'Resultado',
    bestScore: 'Melhor',
    played: 'Partidas',
    points: 'pts',
    step: 'Passo',
    quiz: 'Quiz',
    go: 'Ir',
  },
  fr: {
    header: 'Défi quiz',
    questionsTab: 'Questions',
    leaderboardTab: 'Classement',
    globalBoard: 'Classement global',
    localBoard: 'Classement local',
    leaderboardHeading: 'Classement',
    totalPlayersLabel: 'Joueurs totaux',
    gamesPlayedLabel: 'Parties jouées',
    historyHeading: 'Résultats récents',
    historyGlobalAttempts: 'Tentatives globales',
    historyTopRecord: 'Meilleur score',
    historyScored: 'a marqué',
    historyPlayed: 'jouées',
    boardSource: 'Source',
    historyTab: 'Historique',
    setupTitle: 'Prêt à jouer ?',
    setupInstructions: '1. Entrez votre nom. 2. Choisissez la difficulté. 3. Choisissez votre lot de questions.',
    setupSetTitle: 'Choisir le nombre de questions',
    setupDifficultyTitle: 'Choisir la difficulté',
    questionsSuffix: 'questions',
    difficultyEasy: 'Facile',
    difficultyMedium: 'Moyenne',
    difficultyHard: 'Difficile',
    difficultyReallyHard: 'Très difficile',
    difficultyRandom: 'Aléatoire',
    nameLabel: 'Nom',
    namePlaceholder: 'Entrez votre nom',
    nameRequired: 'Entrez votre nom avant de commencer.',
    difficultyFirst: 'Choisissez la difficulté d’abord',
    modeLabel: 'Mode',
    difficultyLabel: 'Difficulté',
    mode10: '10 questions',
    mode25: '25 questions',
    randomBell: 'Aléatoire',
    returnMenu: 'Retour au menu',
    returnMenuConfirmTitle: 'Quitter le quiz ?',
    returnMenuConfirmBody: 'Votre partie en cours sera perdue et vous reviendrez au début.',
    stayQuiz: 'Rester',
    leaveQuiz: 'Quitter',
    start: 'Lancer le quiz',
    score: 'Score',
    question: 'Question',
    difficulty: 'Difficulté',
    timeLeft: 'Temps',
    nextUp: 'Question suivante...',
    correct: 'Correct',
    wrong: 'Faux',
    timeout: 'Temps écoulé',
    finalScore: 'Score final',
    playAgain: 'Rejouer',
    noLeaderboard: 'Aucun score pour le moment.',
    historyTitle: 'Historique récent',
    noHistory: 'Pas encore d’historique.',
    historyDifficulty: 'Mode',
    historySet: 'Set',
    historyResult: 'Résultat',
    bestScore: 'Meilleur',
    played: 'Parties',
    points: 'pts',
    step: 'Étape',
    quiz: 'Quiz',
    go: 'Go',
  },
  de: {
    header: 'Quiz-challenge',
    questionsTab: 'Fragen',
    leaderboardTab: 'Rangliste',
    globalBoard: 'Globale Rangliste',
    localBoard: 'Lokale Rangliste',
    leaderboardHeading: 'Rangliste',
    totalPlayersLabel: 'Spieler insgesamt',
    gamesPlayedLabel: 'Gesamte Spiele',
    historyHeading: 'Letzte Einträge',
    historyGlobalAttempts: 'Globale Versuche',
    historyTopRecord: 'Bestwert',
    historyScored: 'erzielte',
    historyPlayed: 'gespielt',
    boardSource: 'Quelle',
    historyTab: 'Verlauf',
    setupTitle: 'Bereit zum Spielen?',
    setupInstructions: '1. Namen eingeben. 2. Schwierigkeit wählen. 3. Fragenpaket wählen.',
    setupSetTitle: 'Anzahl der Fragen wählen',
    setupDifficultyTitle: 'Schwierigkeit wählen',
    questionsSuffix: 'fragen',
    difficultyEasy: 'Leicht',
    difficultyMedium: 'Mittel',
    difficultyHard: 'Schwer',
    difficultyReallyHard: 'Sehr schwer',
    difficultyRandom: 'Zufall',
    nameLabel: 'Name',
    namePlaceholder: 'Namen eingeben',
    nameRequired: 'Bitte gib deinen Namen ein, bevor du startest.',
    difficultyFirst: 'Wähle zuerst die Schwierigkeit',
    modeLabel: 'Modus',
    difficultyLabel: 'Schwierigkeit',
    mode10: '10 Fragen',
    mode25: '25 Fragen',
    randomBell: 'Zufall',
    returnMenu: 'Zum Menü',
    returnMenuConfirmTitle: 'Aktuelles Quiz verlassen?',
    returnMenuConfirmBody: 'Dein aktueller Lauf wird verworfen und du gehst zurück zum Start.',
    stayQuiz: 'Bleiben',
    leaveQuiz: 'Verlassen',
    start: 'Quiz starten',
    score: 'Punkte',
    question: 'Frage',
    difficulty: 'Schwierigkeit',
    timeLeft: 'Zeit',
    nextUp: 'Nächste Frage...',
    correct: 'Richtig',
    wrong: 'Falsch',
    timeout: 'Zeit abgelaufen',
    finalScore: 'Endpunktzahl',
    playAgain: 'Nochmal spielen',
    noLeaderboard: 'Noch keine Einträge.',
    historyTitle: 'Letzte Spiele',
    noHistory: 'Noch kein Verlauf.',
    historyDifficulty: 'Modus',
    historySet: 'Set',
    historyResult: 'Ergebnis',
    bestScore: 'Best',
    played: 'Gespielt',
    points: 'Pkt',
    step: 'Schritt',
    quiz: 'Quiz',
    go: 'Los',
  },
  it: {
    header: 'Sfida quiz',
    questionsTab: 'Domande',
    leaderboardTab: 'Classifica',
    globalBoard: 'Classifica globale',
    localBoard: 'Classifica locale',
    leaderboardHeading: 'Classifica',
    totalPlayersLabel: 'Giocatori totali',
    gamesPlayedLabel: 'Partite giocate',
    historyHeading: 'Record recenti',
    historyGlobalAttempts: 'Tentativi globali',
    historyTopRecord: 'Miglior risultato',
    historyScored: 'ha segnato',
    historyPlayed: 'giocate',
    boardSource: 'Fonte',
    historyTab: 'Cronologia',
    setupTitle: 'Pronto a giocare?',
    setupInstructions: '1. Inserisci il tuo nome. 2. Scegli la difficoltà. 3. Scegli il set di domande.',
    setupSetTitle: 'Scegli il numero di domande',
    setupDifficultyTitle: 'Scegli difficoltà',
    questionsSuffix: 'domande',
    difficultyEasy: 'Facile',
    difficultyMedium: 'Medio',
    difficultyHard: 'Difficile',
    difficultyReallyHard: 'Molto difficile',
    difficultyRandom: 'Casuale',
    nameLabel: 'Nome',
    namePlaceholder: 'Inserisci il tuo nome',
    nameRequired: 'Inserisci il tuo nome prima di iniziare.',
    difficultyFirst: 'Scegli prima la difficoltà',
    modeLabel: 'Modalità',
    difficultyLabel: 'Difficoltà',
    mode10: '10 domande',
    mode25: '25 domande',
    randomBell: 'Casuale',
    returnMenu: 'Torna al menu',
    returnMenuConfirmTitle: 'Lasciare il quiz?',
    returnMenuConfirmBody: 'La partita attuale verrà annullata e tornerai alla schermata iniziale.',
    stayQuiz: 'Resta',
    leaveQuiz: 'Esci',
    start: 'Avvia quiz',
    score: 'Punteggio',
    question: 'Domanda',
    difficulty: 'Difficoltà',
    timeLeft: 'Tempo',
    nextUp: 'Prossima domanda...',
    correct: 'Corretto',
    wrong: 'Sbagliato',
    timeout: 'Tempo scaduto',
    finalScore: 'Punteggio finale',
    playAgain: 'Gioca ancora',
    noLeaderboard: 'Nessun punteggio per ora.',
    historyTitle: 'Cronologia recente',
    noHistory: 'Nessuna cronologia.',
    historyDifficulty: 'Modalità',
    historySet: 'Set',
    historyResult: 'Risultato',
    bestScore: 'Migliore',
    played: 'Partite',
    points: 'pt',
    step: 'Passaggio',
    quiz: 'Quiz',
    go: 'Via',
  },
};
